### PR TITLE
Fix update status icon after reverting changes playlist

### LINKED ISSUE #174: Playlist tab does not resume its pre-edit display status
Playlist tab does not resume its pre-edit display status, when playlist changes are discarded. 

For more information, please view this screenshot:

**[Playlist tab not refreshing one playlist changes are discarded](https://user-images.githubusercontent.com/65730626/235909886-bcef9019-a08a-4fd5-99ad-09efd3b10333.png)**

### PR DESCRIPTION
**Pull request by Borewit**
Resolves #174

### CODE REVIEW

**Comment by Borewit** [comment]
Does [this](https://github.com/Borewit/listFix/pull/176#issuecomment-1537090295) solve your problem accessing build artifacts @touwys?

**Comment by touwys** [comment]
> Does [this](https://github.com/Borewit/listFix/pull/176#issuecomment-1537090295) solve your problem accessing build artifacts

Yes, now looking good: 

image

Here is something else I spotted, about the Windows Setup Dialogue, that you may wish to take care of:

image

•••

**Comment by touwys** [comment]
> Does [this](https://github.com/Borewit/listFix/pull/176#issuecomment-1537090295) solve your problem accessing build artifacts

Yes, now looking good: 

image

Here is something else I spotted — about the Windows Setup Dialogue — that you may wish to take care of:

image


•••

**Comment by Borewit** [comment]
> Here is something else I spotted — about the Windows Setup Dialogue — that you may wish to take care of

I have very little control on the [Java packager](https://en.wikipedia.org/wiki/Java_packager) installation process other then passing some basic parameters.

**Pull request merged**
