### PR TITLE
Be able to drag new media directories into the media-list

### PR DESCRIPTION
**Pull request by Borewit**

### CODE REVIEW

**Comment by Borewit** [comment]
Build [listFix_2.6.0-PR147-44.exe](https://workupload.com/file/AcXSBmyvHm7)

**Comment by touwys** [comment]
**Review: listFix_2.6.0-PR147-44**

👉🏻 _Dragging new media directories into the media-directory panel works, but with the following two issues — as per screenshots:_

1. GUI display issue upon change the font style from the default. This is a repeating issue that we are already aware of. It's still to be taken care of, later?

**[Screenshot 1.](https://user-images.githubusercontent.com/65730626/229272153-c4bd1fbb-4a3b-4eb3-b5c7-0aa534f463d4.png)**

_____

2. Reminder Dialogue: The applicable action did not perform as intended. Out of the 4 subdirectories that were added by drag & drop, only the first one was removed. The action did not proceed beyond this point, i.e. 3 of 4 listed subdirectories remained visible in the panel, and the main directory containing them, was not added as it should have been. In addition, these 3 remaining directories had to be removed manually, one by one, as multi-select was unavailable. 

👉🏻 While you're at this, why not consider adding a "Close/Remove All" keyboard shortcut with which to close all the added media directories, which are currently presented in the in this panel, simultaneously?

**[Screenshot 2.](https://user-images.githubusercontent.com/65730626/229272928-c5706215-3e09-4ce3-96e9-88c79d338242.png)**

_____

**Comment by Borewit** [comment]
> GUI display issue upon change the font style from the default. This is a repeating issue that we are already aware of. It's still to be taken care of, later?

Then an issue should be raised to address it, it does not belong in this PR.

**Comment by touwys** [comment]
I was still busy posting when our power supply was cut. Here is the log file, applicable to this review:

•
[rollingfile.log](https://github.com/Borewit/listFix/files/11129173/rollingfile.log)
•

**Comment by Borewit** [comment]
Build [listFix_2.6.0-PR147-47.exe](https://workupload.com/file/jcbkQrTYwbY)

**Comment by touwys** [comment]
**Review: listFix_2.6.0-PR147-47**

✔️ ***All good to go!***

👍🏻 I do like the way you've streamlined the action by having it auto-remove the preloaded subdirectories as soon as their mother-directory gets dragged onto the media directory panel:

image

❓ May I propose an alternative phrase for the "Reminder" dialogue above? _What about this_:

***Removed 2 media directories duplicated in the directories you have added.***

_____

❓ I also noticed a considerable speed increase in the loading of the media directories. Is it my imagination? If not, how did you achieve that?
_______

•
[rollingfile.log](https://github.com/Borewit/listFix/files/11129731/rollingfile.log)
•

**Comment by Borewit** [comment]
> ❓ May I propose an alternative phrase for the "Reminder" dialogue above? _What about this_:

I changes it to: _"Removed %d duplicated media directories"_ and I changed the dialog title _"Reminder"_ to _"Notification"_.

> ❓ I also noticed a considerable speed increase in the loading of the media directories. Is it my imagination? If not, how did you achieve that?

Nothing in this PR what could have increased the speed.

**Pull request merged**
