### PR TITLE
Migrate the application init files to JSON

### PR DESCRIPTION
**Pull request by Borewit**
Existing `.ini` files will **not** be converted.
- Migrate the application the following `.ini` files to `.json`:
   - `%USERPFILE%\.listFix()\dirLists.ini` with `%USERPFILE%\.listFix()\mediaLibrary.json`
   - `%USERPFILE%\.listFix()\history.ini` with `%USERPFILE%\.listFix()\history.json`
   - - `%USERPFILE%\.listFix()\options.ini` with `%USERPFILE%\.listFix()\options.json`
- Removed `.ini` file conversions

### CODE REVIEW

**Comment by Borewit** [comment]
@touwys are you able to test this beta release?

_Deleted_ listFix-2.5.0.zip

Changes are drastic and I have hardly tested anything myself. So expect problems.

**Comment by touwys** [comment]
Thank you, and thank you! I surely will do it, as far as my (very) limited experience allows. It may take a few days however, before I am able to report back.

----------------------------------------

13 Jan 2023 20:21:34 Borewit ***@***.***>:

**Comment by touwys** [comment]
I downloaded listFix-2.5.0.zip. Uninstalled v2.4.0.

To which directory do I have to unzip the v2.5.0 folder? Anywhere in particular?

I installed it here: c:/portable/listFix-2.5.0

then proceeded to run "listFix-2.5.0.jar", which I presumed to be the executable, but nothing actuated.

Did I follow the correct steps? Apologies for my ignorance.

_Footnote: jre1.8.0_351_

**Comment by Borewit** [comment]
There was an [issue building the Windows executable](https://github.com/Borewit/listFix/issues/21), which I have [now fixed](https://github.com/Borewit/listFix/pull/20).
Let me prepare an easier deployment...

**Comment by Borewit** [comment]
I am going to do things in a few smaller steps. I suspect you have run into [this issue](https://github.com/Borewit/listFix/issues/24), and I will do the very minimum to code first trying to address that. Lot of work to even be able to build the code, as dependencies have changed (also vanished / now behave differently).

**Comment by Borewit** [comment]
@touwys can you also try this beta release: [2.4.1-1](https://github.com/Borewit/listFix/releases/tag/beta_version_2.4.1-1)?

**Comment by touwys** [comment]
> @touwys can you also try this beta release: [2.4.1-1](https://github.com/Borewit/listFix/releases/tag/beta_version_2.4.1-1)?

Good show! Thank you. 😁

I installed v2.4.1 moments ago, and now I can add the Media and Playlist Directories without a hitch. I will play around some more, and let you know if something else crops up. Meanwhile, keep me posted on what more you want me to do?

(BTW: I emailed the above reply including a screenshot almost immediately after downloading and installing, but failed to display here).

**Comment by Borewit** [comment]
Glad to hear things are working. If you can give me a clear confirmation [2.4.1-1](https://github.com/Borewit/listFix/releases/tag/beta_version_2.4.1-1) (which is 2.4.1 + this Pull Request(PR))  is at least as good as [2.4.1](https://github.com/Borewit/listFix/releases/tag/2.4.1). No rush, please take time to test it. 

And in the issues you created, #14, #15 if they are resolved with any of those versions.  So feedback regarding [2.4.1](https://github.com/Borewit/listFix/releases/tag/2.4.1) is best to place there, because then I know if those issues are resolved or not.

**Comment by touwys** [comment]
Will do. (This time it may indeed take a little while longer, due to our restricted national electrical power supply. It's a [nightmare](https://www.politicsweb.co.za/politics/south-africans-must-take-to-streets-over-electrici).)

**Comment by touwys** [comment]
@Borewit:

I installed v2.4.1-1 without first uninstalling v2.4.1. The results of the first few quick tests, are as follows:

1. **The Media Directories failed to be added — as it previously did with v2.4.0**.
2. The addition of the default Playlist Directories (in Options) was successful.
3. The option to change the default app Skin was successful, unlike in v2.4.0 which caused the app to hang.

_A clean installation of v2.4.1-1 required?_ (Possible corruption of config files ini_json?)

**Comment by touwys** [comment]
@Borewit:

I did a clean reinstallation of v2.4.1-1, with the same initial results as already noted.

I have one query, though (also view the screenshot):

How is it possible for a playlist to be verified as "OK" or "!" in the absence of the Media Directories?

**Comment by touwys** [comment]
@Borewit:

You are really swinging it! 

**listFix() v2.4.2 — The issues that presented in the preceding versions, are now gone. Great job, and fast!**

Thank you. 

_Anything else in particular that you want me to test for?_

**Comment by Borewit** [comment]
Thanks for you detailed review @touwys, very useful. Based on your findings on [v2.4.1-1](https://github.com/Borewit/listFix/releases/tag/beta_version_2.4.1-1), this PR seems to reintroduce issues with adding media directories. I hope I will be able to reproduce those issues. 

I did some testing on [v2.4.1-1](https://github.com/Borewit/listFix/releases/tag/beta_version_2.4.1-1) myself, by fixing some of my playlists. At a certain point I run into an Exception.

**Comment by Borewit** [comment]
@touwys, can you find any issue is this release: [beta-v2.4.2-2](https://github.com/Borewit/listFix/releases/tag/beta-v2.4.2-2)

**Comment by touwys** [comment]
> @touwys, can you find any issue is this release: [beta-v2.4.2-2](https://github.com/Borewit/listFix/releases/edit/beta-v2.4.2-2)

@Borewit: I'm sorry, but I'm unable to locate the download link for listFix() beta-v2.4.2-2 on the given page. Can you perhaps provide a direct download link for it?

Thanks.

**Comment by Borewit** [comment]
> I'm sorry, but I'm unable to locate the download link for listFix() beta-v2.4.2-2 on the given page.

My mistake, forgot to submit the page.

> Can you perhaps provide a direct download link for it?

Release is to big to toss it into an issue, something like 25MB what is allowed, but yeah can be done with some third party service.

**Comment by touwys** [comment]
Thanks, will download, test and report accordingly. I also inadvertently deleted my previous post, sorry.

**Comment by touwys** [comment]
@Borewit :

**Re listFix() v4.2.2-2:**

I stopped testing after the first run. There appears to be a regression to [Media Directories Cannot be Added · Issue #15](https://github.com/Borewit/listFix/issues/15) · Borewit/listFix. It was impossible to add any — there appeared only a short flash of "something" across the screen.

The "Playlist Directories", and the "Skin" options were still capable of being set. That is as far as the current testing went.

**Comment by touwys** [comment]
**Something else I have noticed after installing beta-v2.4.2-2:**

All the configuration settings from v2.4.2 have disappeared. Was it intentional? Please advise what is best practice in this case: should I uninstall the previous version first, by default, before installing the newer one?

Thanks.

**Comment by Borewit** [comment]
> All the configuration settings from v2.4.2 have disappeared. Was it intentional?

Yes, see the [PR description](https://github.com/Borewit/listFix/pull/19)

> should I uninstall the previous version first

In principal not. Unless you experience issues you can try that.

I have got another beta release: [listFix_2.4.2-3.exe](https://filetransfer.io/data-package/B7bxyYgy#link).

> It was impossible to add any

The last release worked fine for me, also auto repairing playlists using exact match.
If you run into issue, try to delete `%USERPFILE%\.listFix()\*`, and then you need to reconfigure everything...

**Comment by touwys** [comment]
> I have got another beta release: [listFix_2.4.2-3.exe](https://filetransfer.io/data-package/B7bxyYgy#link).

Please check that the download link is accessible? It directs to a page flagging error messages ("file not found" / "secure connection failed") while trying to download it from two different devices, i.e. a Windows PC and an Android tablet. 


> If you run into issue, try to delete `%USERPFILE%\.listFix()\*`, and then you need to reconfigure everything...

I deleted this folder for v2.4.2-2, restarted the app, and first action was to add the Media Directories. Now would. Same error. I am thus going to uninstall this version, and run v2.4.2-3 as soon as it is available for me to download.

**Comment by touwys** [comment]
@Borewit :

Another observation: I removed listFix v2.4.2-2 again to make another clean installation of it to see if it perhaps would make any difference to the matter at hand. What I did notice when the installer was starting to run, is that the **listFix v2.4.1-0 installer window is displayed — instead of v2.4.2-2**. 

**Screenshot**

listfix 2 4 1-0 installer window display for v2 4 2-2 _ Screenshot 20230118_1

**Comment by Borewit** [comment]
> I have got another beta release: [listFix_2.4.2-3.exe](https://filetransfer.io/data-package/B7bxyYgy#link).

Please double check the link, I had that issues with the attempt, file seem to vanish there. This link, as the one in your reply should work....

If really it does not work, your location must be blocked, then we need to find a more reliable file cloud provider.

Yeah I reverse engineered the original PNG to an [SVG](https://github.com/Borewit/listFix/blob/main/src/main/svg/listFix()%20logo.svg), in which I can now change the version numbers. Yet the generation of the PNG from the SVG is not done automatically at build time. I will pay more attention when doing a formal build.

**Comment by touwys** [comment]
> I have got another beta release: [listFix_2.4.2-3.exe](https://filetransfer.io/data-package/B7bxyYgy#link).

Thank you, I got this one downloaded to my tablet. We're amidst another scheduled power blackout, therefore I can only get it onto my PC earliest tomorrow.

If we continue to experience files storage and download problems, it's easy enough to use another.

**Comment by touwys** [comment]
@Borewit —

**Re: listFix_2.4.2-3**

_On first use:_

1. Media Directories add — Yes.
2. Playlist Directory set — Yes.
3. Menu > "Open Playlist" — Yes
4. Skin changeable — Yes.
5. "Fix Everything" — NO (see error message in screenshot provided).
6. "Find Exact Matches" — NO (same issue as before — if I correctly understand how this command should be executed).

The aforesaid is what I had tested so far, and will pause here until receiving your further instructions.

Thank you.

**Screenshot:**

image

**Comment by touwys** [comment]
@Borewit:

There are also issues, today, with the download link you provided for listFix_2.4.2-3. Is there perhaps a timed delay after which the download link expires?

Here are some file sharing options which we could possibly consider — unless you prefer to use Telegram Messenger:

<a title="File sharing and storage made simple" href="https://www.mediafire.com/">MediaFire</a>

<a title="Zippyshare.com - Free File Hosting" href="https://zippyshare.com/">Zippyshare</a>

<a title="FileFactory" href="https://www.filefactory.com/">FileFactory</a>

<a title="DepositFiles" href="https://depositfiles.com/">DepositFiles</a>

<a title="Send Anywhere - File transfer" href="https://send-anywhere.com/">Send Anywhere</a>

<a title="workupload - Share and send large files." href="https://workupload.com/">Workupload</a>

<a title="Ufile.io - Upload files for free &amp; share them without registration" href="https://ufile.io/">Ufile</a>

**Comment by Borewit** [comment]
So fixing the playlists throws error.

I already moved in the mean time.
I thought I tested fixing playlists in 2.4.2-3 and so I tried again after moving on, both the _fix everything_ and _exact match fix_ worked fine for me on a broken playlist and a long playlist.

I pushed these changes and made another build [listFix_2.4.2-4](https://www.mediafire.com/file/nqr5vzscir293jk/listFix_2.4.2-4.exe/file)

I have already changes 2500 hundred lines of code and I still think there is a lot to improve. We call that _refactoring_ in which it very easy to create new bugs. I keep an eye on things you report, but I will blindly keep refactoring until the code reaches, in my view, a reasonable quality. There is so much duplicated code, bad object design

The other big thing what needs to happen in the project, it is depend on licensed GUI component so it may not even be legal as free / open source project. Besides that, I cannot update that ancient dependency. So parts of the front-end need to be rewritten.

I am traveling for work for more then a week, so things will not move for a while.

Thanks for your detailed reviews @touwys.

**Comment by touwys** [comment]
@Borewit :

I am very grateful for your continued effort to revive the app and streamline the code, which, given your very upbeat perspective, I am sure, is going to deliver a solid, desirable end-product. That you are continuing to develop listFix() regardless of its current, said moderate use, is simply awesome. I imagine that if listFix() was deservedly promoted over time, it would have been another story altogether, as there apparently do not exist a competitive product.


> I pushed these changes and made another build [listFix_2.4.2-4](https://www.mediafire.com/file/nqr5vzscir293jk/listFix_2.4.2-4.exe/file)

The download experience of listFix_2.4.2-4 from the new file host, was effortless. Thank you. I will try this version as soon as I can.


> I am traveling for work for more then a week, so things will not move for a while.

Have a safe trip next week, and may it deliver the desired results for you. Meanwhile, I will continue to post my incremental test results here, and then you can attend to it as and when you can.

Thank you.

**Comment by touwys** [comment]
**listFix_2.4.2-4:**

Report:

After the opening start:

1. Media Directories; add — Yes
2. Playlist Directory; set — Yes
3. Open Playlist; — Yes
4. Fix Everything; — Yes
5. Find Exact Matches; **— NO** _[Progress window still flashes and disappears; the action is not executed]_
6. Open a playlist:
6.1 Right-click on a track to open the context menu
6.2 Select Preview PLAY. _[This command is not executed, even though'the default music player has been set]_

**Comment by touwys** [comment]
**listFix_2.4.2-4:**

Upon further testing, I observed this about Item #5, **"Find Exact Matches"**, in the previous post:

When this command is executed by clicking on the binocular-icon situated on the toolbar above the open playlist, the command fails straight away — as previously described. However, whenever it is executed from the playlist context menu which opens by right-clicking on a playlist on display in the Playlist Directory pane, the command is PARTIALLY successful in execution. This is best explained by the screen video, which I have uploaded for you **[here](https://workupload.com/file/MuxUycsLVHE)**. The download link expires in one day from now, and the file can be downloaded once only. (I am trying this file storage service to see whether it is useful.)

**Comment by Borewit** [comment]
Thanks again for your review @touwys. 
It is so weird that the find exact matches works for me and not for you,

> Find Exact Matches; — NO [Progress window still flashes and disappears; the action is not executed]
Open a playlist:
6.1 Right-click on a track to open the context menu
6.2 Select Preview PLAY. [This command is not executed, even though'the default music player has been set]

Are these 2 issue introduced by this PR ([listFix_2.4.2-4](https://www.mediafire.com/file/nqr5vzscir293jk/listFix_2.4.2-4.exe/file))? Or do you have the same behavior if you switch back to [v2.4.2](https://github.com/Borewit/listFix/releases/tag/v2.4.2). Which is maybe tricky to compare as the configuration files are different.

When I am back I will try to replicate your setup. The only significant difference I can come up with, is that I have tested with network paths (`\\diskstation\music` as my media library and `\\diskstation\music\_playlists`)  while you are using drive path. Maybe first thing to try is to mount `\\diskstation\music` as `W:` and see if thing break.

**Comment by touwys** [comment]
> Are these 2 issue introduced by this PR (listFix_2.4.2-4)? Or do you have the same behavior if you switch back to v2.4.2. Which is maybe tricky to compare as the configuration files are different.

I have tested the "Find Exact Matches" playlist fix using the context menu of the playlist located in the playlist directory, for the first time with listFix_2.4.2-4. Thus I have no way of telling whether there is a difference, sorry. Do you need me to go back to v2.4.2 to test and see what happens, or shall we wait to see what you come up with? There really is no need for you to rush it. I am also testing the app in small increments, and carry on learning more about it as I do. As it is right now, the very basics are usable and useful — up to the point I have tested it.

**Comment by Borewit** [comment]
The reason I am asking, is to asses if this PR creates new issues. In that case I should solve them as part of this PR.

If it are existing issue you run into, I can merge, release a formal version, and address the individual bugs in smaller focussed PR's.

**Comment by touwys** [comment]
> The reason I am asking, is to asses if this PR creates new issues. In that case I should solve them as part of this PR.
> 
> If it are existing issue you run into, I can merge, release a formal version, and address the individual bugs in smaller focussed PR's.

@Borewit :

**I have gone back, removed listFix_2.4.2-4, and reinstalled listFix_2.4.2:** 

**Result:**

1. The Media and Playlist Directories added all right, just as it did previously.

2. As with listFix_2.4.2-4, the "Find Exact Matches" playlist fix from the **context menu** of the playlist located in the playlist directory, calls up the "Exact Matches Search" sub-window. Subsequently, I opened the appropriate playlist, and initiated the "Find Exact Matches" command (binocular icon). As with listFix_2.4.2-4, only a very brief display of what appears to be a progress bar, is flashed on the screen appears, and the disappears. Nothing else happens.

I only tested the aforesaid, nothing more, awaiting your further instructions.

**Comment by Borewit** [comment]
So then we can assume this PR does not introduce any new issues, the issues you experienced had already been there.

In that case, if you don't mind, please open a new issue (you can convert one of your comments) into a new issue.

And please create another issue for failing to play tracks.

Steps to possibly reproduce the issue are very much welcomed.

If you do somehow manage to get the auto fix functions working, you maybe able to narrow down that problem.

**Comment by touwys** [comment]
**Testing listFix() version 2.4.2:**

> If you do somehow manage to get the auto fix functions working, you maybe able to narrow down that problem.

With "auto fix" functions, are you in fact referring to the "Fix Everything" (magic wand icon) function? If so, executing operations with **"Fixed Everything"**, listFix() version 2.4.2 will now:

1. Find/Select the closest matches in a broken playlist.

2. Preview>Play the individual tracks it found.

_In addition_, listFix() version 2.4.2 will now also play individual tracks, as well as the complete playlist that is open for repair. 

@Borewit : Certainly, this is some good news to start the week with. I wonder, though, why the Preview>Play was dysfunctional, before?

_Residual:_

3. The "Find Exact Matches" (binocular icon) issue persists. However, since such a considerable time has elapsed since the app was broken for me, I do not remember quite what happens, or what to expect, after this command is executed. Therefore, before I proceed to post it as a separate issue, could you perhaps upload a screen video of the actions after applying this command?

4. Please bear in mind to fix the version number displayed in the start-up splash window for listFix() version 2.4.2 — it displays listFix() version 2.4.1-0 as shown in an earlier post.

**Comment by Borewit** [comment]
It is still not clear to me if this PR is introducing any issue [touwys](https://github.com/touwys).

I did came across 1 issue though while testing, that normalizing the playlist to UNC file path throws [ConcurrentModificationException](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/ConcurrentModificationException.html) which was introduced by this PR and which now fixed with 7d4847270cbfb988b57148ba741e5d4a99f79372.


Using the _Find exact matched_ and the _Fix everything_ works for me on this PR and on 2.4.2.

I tried that on:
- UNC path: `\\diskstation\music`


- Network drive: `M:\`


- Local drive: `C:\Users\Borewit\music`


Playing tracks from the playlists works for me for both in 2.4.2 and this PR, yet VLC gave an error before playing the file. I [created an issue](https://github.com/Borewit/listFix/issues/30) for that is this is not introduced by this PR and seems to be more of a VLC issue.

Including the last [fix](https://github.com/Borewit/listFix/commit/7d4847270cbfb988b57148ba741e5d4a99f79372), I will create a new temporary release based on this PR.

**Comment by Borewit** [comment]
Beta release: [listFix_2.4.2-5.exe](https://www.mediafire.com/file/6quxmxvnxgp3juo/listFix_2.4.2-5.exe/file) which fixes UNC normalization in this PR.

**Comment by touwys** [comment]
Glad to have you back, @Borewit !

> It is still not clear to me if this PR is introducing any issue [touwys](https://github.com/touwys).

I am somewhat at a loss here. With "this PR", are you referring to listFix_2.4.2-4? I had previously uninstalled it, and then went back to reinstall listFix_2.4.2. Are you working from listFix 2.4.2-4 as basis? I assume you are still busy moving over to the more stable json config settings, hence the new release v2.4.2-5? My apologies, if I do not truly grip what is involved here.

Please, also recommend whether I should uninstall listFix_2.4.2 first, before installing listFix_2.4.2-5 — and whether I should stick to whichever method you recommend, for future releases. (For this one, I am going to go for a clean installation by first removing the installed version.

Thank you!

**Comment by Borewit** [comment]
> I am somewhat at a loss here. With "this PR", are you referring to listFix_2.4.2-4?

Correct, every release I post in this PR.

You can read `listFix_2.4.2-4` as last official version 2.4.2 + 4 changes (commits).
If you scroll to the beginning of this PR, you will see different tabs showing the 4 _Commits_. _File changed_ is showing to actual code changed by those 4 commits.

These [changes](https://github.com/Borewit/listFix/pull/19/files) represent this PR. 

Those commits are done on a _Git branch_ (in this PR that is branch [migrate-appconfig-to-json].
A PR (Pull Request) is a branch + some web features, like the discussion we are having about this branch.

You could see a branch like changes you made to a text file with notepad, but we have not saved those changes yet.
When we merge this PR/branch, you could see it as saved as the changes will then be merged to the default branch.
 
> Are you working from listFix 2.4.2-4 as basis?

So [2.4.2](https://github.com/Borewit/listFix/releases/tag/v2.4.2) is what is currently on the default branch. Depending what you mean with _basis_, that is the last version on the default branch. Well, almost, actually I have 1 change on the default branch since v2.4.2. That is why we have now 4 changes in this branch, and we are on release listFix_2.4.2-5.

But listFix_2.4.2-5 is based on listFix 2.4.2-4 indeed: listFix_2.4.2-5 = listFix 2.4.2-4 + fix UNC normalization (commit #4 on this branch, commit #5 since 2.4.2).

> Please, also recommend whether I should uninstall listFix_2.4.2

May be safer indeed.

**Comment by touwys** [comment]
All of navigating GitHub, and the corresponding language used by developers, may come natural to you guys, but believe me, to the uninitiated, this is all a very strange, if confusing experience.

Anyway, I have already completed the clean installation of listFix_2.4.2-5. I have gone only thus far, and this is what I found:

1. The Media Directories plus Playlist Directory added properly.

2. "Select Closest Matches" > "Preview" >"Play". Again, now does not call the default player. Perhaps consider to later add an programme Option to select any player?

3. "Find Exact Matches" (binocular icon) behaves the same as before — it briefly flashes on the screen what appears to be a progress window that says "Repairing", but it disappears instantly.

(I still need to know what exactly I should look out for when activating the "Find Exact Matches" action. Should it open a window, just like "Fix Everything" does — but only for **exact** matches? I can't remember it from way back.)

**Comment by Borewit** [comment]
> All of navigating GitHub, and the corresponding language used by developers, may come natural to you guys, but believe me, to the uninitiated, this is all a very strange, if confusing experience.

Fully understand that, it is not easy.

> 2. "Select Closest Matches" > "Preview" >"Play". Again, now does not call the default player. Perhaps consider to later add an programme Option to select any player?

Ah, preview play within the "Select Closest Matches", yes I can replicate the issue! Sorry I missed that in earlier observations.

> 3. "Find Exact Matches" (binocular icon) behaves the same as before — it briefly flashes on the screen what appears to be a progress window that says "Repairing", but it disappears instantly.

Can you please try to create a test environment somewhere on `C:\`? Copy a bunch of audio files to a test folder, create a playlist from the audio files. Move the files to a sub-directory, to deliberately break the playlist and re-try the "Select Closest Matches".

The goal is to get in working on your machine. If you manage to get in working, we can start to figure out under what condition it breaks.

**Comment by Borewit** [comment]
> 2. "Select Closest Matches" > "Preview" >"Play". Again, now does not call the default player. Perhaps consider to later add an programme Option to select any player?

This issue seems to be introduced by this PR.

**Comment by touwys** [comment]
> > 2. "Select Closest Matches" > "Preview" >"Play". Again, now does not call the default player. Perhaps consider to later add an programme Option to select any player?
> 
> This issue seems to be introduced by this PR.

Yes, it worked properly in listFix_2.4.2

**Comment by touwys** [comment]
> Can you please try to create a test environment somewhere on `C:\`? Copy a bunch of audio files to a test folder, create a playlist from the audio files. Move the files to a sub-directory, to deliberately break the playlist and re-try the "Select Closest Matches".

Starting this tomorrow.

**Comment by Borewit** [comment]
This version should fix `NullPointerException`, when:

> Right click on playlist entry, select "Find Closest Matches" > In "Preview" click "Play" button.

image

[listFix_2.4.2-7.exe](https://www.mediafire.com/file/uq7hrf52mgc1psw/listFix_2.4.2-7.exe/file)

**Comment by touwys** [comment]
> to deliberately break the playlist and re-try the "Select Closest Matches".

By "Closest Matches", do you mean "Fix Everything?

**Comment by Borewit** [comment]
> By "Closest Matches", do you mean "Fix Everything?

Updated https://github.com/Borewit/listFix/pull/19#issuecomment-1407692395. 

I copied [your words](https://github.com/Borewit/listFix/pull/19#issuecomment-1407681965) :wink:.

**Comment by touwys** [comment]
> I copied [your words](https://github.com/Borewit/listFix/pull/19#issuecomment-1407681965) wink.

"Closest Matches" is the heading of the window that opens only once "Fix Everything" is activated, it is not an action in itself...  🤔 

Jokes aside, I could not wait, went ahead and installed listFix_2.4.2-7.  Copied 21 audio files over to C:\ and created the playlist, which I then broke by moving the audio files to a subfolder. Both "Fix Everything" and "Find Exact Matches" fixed the broken playlist in an instant. "Preview" > "Play" not tested.

**Comment by Borewit** [comment]
> "Closest Matches" is the heading of the window that opens only once "Fix Everything" is activated, it is not an action in itself... 

What I have fixes in the last update:

image

This is the play I have fixed, which was broken:

image

I thought that is what you meant in https://github.com/Borewit/listFix/pull/19#issuecomment-1407681965, ""Select Closest Matches" > "Preview" >"Play"

**Comment by touwys** [comment]
> I thought that is what you meant in #19 (comment), "Select Closest Matches" > "Preview" >"Play"

Yes, that's the one — only, I engaged it from the menu bar (magic wand icon) while you did it from the playlist context menu. Thus, we agree.

_I have tested "Select Closest Matches" > "Preview" >**"Play"**, and also found it fixed for listFix_2.4.2-7. It called the default player to play the selected track._

Is fixing "Find Exact Matches" next on the test list?

**Comment by Borewit** [comment]
> Is fixing "Find Exact Matches" next on the test list?

Since this issue was already present in v2.4.2 [reported here](https://github.com/Borewit/listFix/pull/19#issuecomment-1400226248), please create a new issue for this.

I am going to merge the PR, and create a formal release.

**Comment by touwys** [comment]
> Since this issue was already present in v2.4.2 reported here, please create a new issue for this.

No problem, but do you mean I have to create an issue other than the same one already posted here?:

**<a title="The &quot;Find Exact Matches&quot; action appears to be dysfunctional? · Issue #28 · Borewit/listFix" href="https://github.com/Borewit/listFix/issues/28">The &quot;Find Exact Matches&quot; action appears to be dysfunctional? · Issue #28 · Borewit/listFix</a>**

**Comment by Borewit** [comment]
Part of [v2.5.0](https://github.com/Borewit/listFix/releases/tag/v2.5.0)

**Comment by Borewit** [comment]
>No problem, but do you mean I have to create an issue other than the same one already posted here?

My bad, no one issue is more then enough.

**Pull request merged**
