### PR TITLE
Drop the "Exact Matches Repair...."

### LINKED ISSUE #154: Drop the "Exact Matches Repair...." feature
The "Repair" menu could be trimmed by removing the first entry, namely: "Exact Matches Repair". This action is already more suitably taken care of in the editor, and it does not really belong here with the other two. 

image

### PR DESCRIPTION
**Pull request by Borewit**
Changes:

1. Drop the "Exact Matches Repair...."
2. Some minor code style improvements

Resolves #154

### CODE REVIEW

**Comment by Borewit** [comment]
Build [listFix_2.7.0-PR157-2.exe](https://workupload.com/file/JsyFpPkc9Xr)

**Comment by touwys** [comment]
> Build [listFix_2.7.0-PR157-2.exe](https://workupload.com/file/JsyFpPkc9Xr)

Looks like bike-mechanic and software developer go hand in hand? 😄 I will grab this build tomorrow.

**Comment by Borewit** [comment]
> Looks like bike-mechanic and software developer go hand in hand? 😄 I will grab this build tomorrow.

Flat tire, glue should be dry by now. Sure, enjoy your evening!

**Comment by touwys** [comment]
**Review: listFix_2.7.0-PR157-2**

1. `Repair > Find Exact Matches` is gone. (Should I have expected a change in the description of the two remaining menu items, in this build?)

2. `Updating the Media Library` with this took much longer than with listFix_2.7.0, and the previous build listFix_2.7.0-PR156-1

❓ _Does it make sense to remove `Find Exact Matches` from the `Repair` menu, while keeping it as a tool in the Playlist Editor? Should we not then consider removing, too, the `Find Exact Matches` command (the binocular icon) from the Playlist Editor, since it is already inherent in the `Fix Everything` command (the magic wand icon)? Additionally, consider whether `Fix Everything` is an apt description for the command? "**Find Closest Matches**" is probably the more apt description for it._

**Comment by Borewit** [comment]
I also thing the "Find Exact Matches" does not make much sense. It does fix / replaces alternative broken entries with "exact" matched found.

What about this?
Fix everything => Find closest matches
Find Exact Matches => Repair playlist

> Updating the Media Library with this took much longer than with listFix_2.7.0, and the previous build listFix_2.7.0-PR156-1

I don't think I have made any changes in the code which explain the difference in performance. After running a Java application for a while, it may become faster, as the[ just-in-time (JIT) compiler](https://developers.redhat.com/articles/2021/06/23/how-jit-compiler-boosts-java-performance-openjdk#) kicks in. Parts of the code run frequently are optimized, which first causing some delay and next time it runs faster. Other effects on negative performance may be caused by anti-virus software, and thing running in the background like Windows updates.

**Comment by Borewit** [comment]
Shall we merge this one and release @touwys?

Or do some [renaming](https://github.com/Borewit/listFix/pull/157#issuecomment-1503981609) first as part of this PR?

**Comment by touwys** [comment]
> Shall we merge this one and release

In my opinion, merge and release. Drop all other forms of searching, or any of the renaming for it. Retain only "Select Closest Matches", as this is really all, and the only action, that really counts — it's the sole reason listFix() exists.  "Select Closest Matches" is already extensive in function, and now nearly complete, and with a dialogue full of usable features to find the best matches. Later, the last piece to fit the accurate search puzzle, the search algorithm, can be reviewed.

_See also #154_

**Comment by Borewit** [comment]
Thank you @touwys for providing a clear focus. Okay, I will strip out the "exact match" everywhere.

**Comment by Borewit** [comment]
Stripped out exact repair.
Renamed _find closest match_ to _repair playlist_.
Build [listFix-windows-exe](https://github.com/Borewit/listFix/suites/12694752815/artifacts/681205801)

**Comment by touwys** [comment]
> Renamed _find closest match_ to _repair playlist_.

Looking good. 

_Off-topic:_ consider if a **command to cancel** the `Menu > Repair > Repair all open playlists` process, constitutes a productive addition? If you agree, I will add to the current crop over at issues.

**Comment by touwys** [comment]
Error found: when the app shortcut is pinned to the Windows Taskbar, it will display a blank icon, instead of the usual listFix logo-icon.

**Pull request merged**
