### PR TITLE
Fix being able to delete folder from Playlists-Directories panel

### LINKED ISSUE #102: Folder in Playlist Directory, does not get cleared after deletion
**listFix() v2.6.0 | Windows 7 x64**

Location: A Folder Presented in the Playlist Directory —

_Steps:_

1. Delete the folder.

2. Close listFix().

3. Restart listFix().

🗒️ _The (empty) folder is still visible in the PLD. It also displays a different icon._

### PR DESCRIPTION
**Pull request by Borewit**
Resolves #102

### CODE REVIEW

**Comment by Borewit** [comment]
Build [listFix_2.6.0-PR114-5.exe](https://www.mediafire.com/file/18zr3a9ntsjykql/listFix_2.6.0-PR114-5.exe/file)

**Comment by touwys** [comment]
**Testing listFix_2.6.0-PR114-5**

**Steps:**

1. Un-installed listFix_2.6.0-[PR106]-5, including deleting "rollingfile.log" file, plus ".listFix()position.ini"

2. Install listFix_2.6.0-PR114-5, and continue with the initial set up of listFix.

3. Drag and drop playlist folders into PLD

ℹ️ _3.1 Not possible yet._

5. Add playlist folder to PLD via Windows Explore.

6. Add Media Directory.

7. Open and change 3 "Options", namely: Look & Feel, Font, Number of closest matches to return.

8. Open, and close immediately, several playlists in PLE.

9. Open 1 playlist in PLE to test various functions:

10. Select the 4 exclusively _unmatched_ tracks out of 12 tracks in total.

11. Click on the "Find Exact Matches" binoculars icon on the PLE toolbar.

ℹ️ _10.1 The progress dialogue is _not_ called up in display. That said, however, 3 out of 4 matches were found almost instantly. This progress dialogue probably need not be displayed if the action is completed so quickly? But, is that consistent to providing GUI progress information to the user?_

ℹ️ _10.2 How do we verify the accuracy of any exact matches found by the action, "Find Exact Matches"? The only test available to check how accurate the match it found is, is after the fact, i.e. _after_ the fix is already in? Of course, if the exact matches found are consistently, perfectly reliable, this is not essential as it is for finding closest matches._ 

12. Select the action: "Reload" to cancel the exact matches found, of Step 10.

13. Select the same 4 _unmatched_ tracks, _again_.

14. This time, call the action "Find Closest Matches" from the _context menu_ of the 4 selected, unmatched, tracks. The closest matches are found and in display. 

ℹ️ _13.1 This action calls an _unnamed_ progress bar, which in turn is followed by displaying the "Select Closest Matches" dialogue, containing the 4 matched tracks._

15. In the "Select Closest Matches" dialogue, call the action: Press Preview / PLAY for each track in turn: 

✔️ _14.1 Default media player now starts, and 4 out of 4 tracks are played back._

16. In the "Select Closest Matches" dialogue, right-click to call "Open File Location" of the best match.

❌ _15.1 There is no reaction. Thus, unavailable for further testing for the problem that was cited here: https://github.com/Borewit/listFix/pull/106#issuecomment-1443590093_

17. Click "Cancel" to close the "Select Closest Matches" dialogue.

18. Select "Fix Everything" magic wand in toolbar to repeat Step 12.

❓ _17.1 Calls first a "Repairing" progress dialogue, which is then followed by "Finding closest matches for all missing files" progress dialogue, which is, in turn, is finally followed by "Select Closest Matches". Is the first dialogue, "Repairing", really needed here? Its display seems to be redundant._

❓ _17.2 Should there not be consistency in the use of dialogues/operations/actions of Steps 15 & 17?

18. PLD > Right-click playlist folder > Context Menu: "Remove Playlist Directory" to remove a playlist folder from the PLD. 

✔️ _18.1 It cleared as expected._

• 
[rollingfile.log](https://github.com/Borewit/listFix/files/10833291/rollingfile.log)
•

**Comment by Borewit** [comment]
> ✔️ 18.1 It cleared as expected.

That was the aim of this PR.

> ✔️ 14.1 Default media player now starts, and 4 out of 4 tracks are played back.

Looks like something kept hanging from the previous installation.

> 5. Add playlist folder to PLD via Windows Explore.

See PR #113

**Comment by touwys** [comment]
> See PR https://github.com/Borewit/listFix/pull/113

I skipped the previous two releases, to go straight on to installing the latest one which, in this case, was listFix_2.6.0-PR114-5. 

❓ _Does the latest release _not_ contain the fixes, etc., of its predecessors? Is this what you meant by a "boxed" approach — i.e. that you wish me to install — without skipping — each release to progressively test only the latest portion of development? If that is indeed the case, I was under the wrong impressions, sorry._

**Comment by Borewit** [comment]
> ❓ Does the latest release not contain the fixes, etc., of its predecessors? Is this what you meant by a "boxed" approach — i.e. that you wish me to install — without skipping — each release to progressively test only the latest portion of development? If that is indeed the case, I was under the wrong impressions, sorry.

Yes @touwys, there is no sequence! There is not one release (yet), which contains all the changes I am working on. Each Pull Request is a **change proposal**, which typically solve only 1 issue at a time! 

Only when the PR is merged, I can possibly re-stack (we call that _rebasing_) other open PR's on top the merged change.

So each PR has a title, that title should explain what the change is about.
This one is _Fix being able to delete folder from Playlists-Directories panel_, so these [changes](https://github.com/Borewit/listFix/pull/114/files) are about that. It also links to an issue, which is: _Folder in Playlist Directory, does not get cleared after deletion_. That issue is automatically closed when this PR is merged. 

So every PR is typcially reviewed before merging. The testing you do with the PR builds, is a form of reviewing that PR.
The testing you do with the PR builds, is reviewing that PR.  

That also explains why it safe to invite other developers.  They can only _propose_ code changes via a PR, as the owner of the repository, I will decide at the end if I merge that change.

**Comment by touwys** [comment]
Thank you, @Borewit, for a good explanation. I'm beginning to see how it ties together, branches and all. I have now downloaded the two skipped releases, and will test those, as soon as I can. _Do you still need them to be tested, though?_

In addition, and just to make sure again — is it OK to install over another PR-release, or do you prefer a clean install everytime? Since there is, strictly speaking, no sequence to the PR-releases, I presume that a clean install is not required.

**Comment by Borewit** [comment]
> is it OK to install over another PR-release, or do you prefer a clean install every time?

I am not sure how reliable install de-install process is. I usually run everything from my development environment. 
I may be enough just to run the new installer. In double, you can probably check the in dates in the installation directory, if the files have been replaces.

**Comment by touwys** [comment]
The uninstaller software I use, is quite advanced, as well as reliable. To err on the safe side, I will opt to do a clean install everytime. I do not mind reconfiguring the app again; it only takes a moment, or two.

> I have now downloaded the two skipped releases, and will test those, as soon as I can. Do you still need them to be tested, though?

Do you?

**Comment by Borewit** [comment]
> Do you still need them to be tested, though?

Yes please, if the PR is open and it is about user functionality, please check. It is so easy to make mistakes there, and if you requested the change, good to confirm it is meeting your requirements.

**Pull request merged**
