### PR TITLE
Remove the "ancient PC" optimization

### PR DESCRIPTION
**Pull request by Borewit**
Removes the [_"ancient PC optimization"_] and replaces it with a much short lambda expression.

### CODE REVIEW

**Comment by Borewit** [comment]
I am just curious @touwys, this PR removes the [_"ancient PC optimization"_](https://github.com/Borewit/listFix/pull/203#issuecomment-1734083904), are you able repeat the [same test](https://github.com/Borewit/listFix/pull/203#issuecomment-1734083904)?

Reviewing this PR has no priority at all.

Expected result: it may take a little longer to find the best matches.

**Comment by touwys** [comment]
> I am just curious @touwys, this PR removes the "ancient PC optimization", are you able repeat the same test?

Yes, I am. Can take care of it on Tuesday, 26th.

**Comment by touwys** [comment]
@Borewit :

### listFix()-2.8.1-5

The ancient pc speed test could not be brought to a successful conclusion, due to an issue that repeatedly broke the repair process. Namely, the repair process stopped immediately after having first completed finding the exact matches. Finding the exact matches was therefore not naturally followed by the next part of the process, i.e. finding the closest matches. There were no other visible clues to this occurrence, but the stop.

Nevertheless, the test was completed using the identical setup as before, and inasmuch as it concerns testing the speed of finding only the exact matches.

### Setup

1. Windows 7 x64 PC with a 4-core Intel Core i7-3770K CPU.
2. Two different processing speed tests were run with the same playlist.
3. The playlist contains 631 fully broken mp3 tracks calling for matches.
4. The tests were timed. 
5. For the first test, the Media Directory (MD) panel incorporated both a mp3 and FLAC library. 
6. For the second test, the FLAC directory was removed from the MD.

### Results

**Test 1**

|   Find Exact	|Find Closest   	| Total  	|
|---	|---	|---	|
|   	1m 7s|  issue-stopped 	|   	|

**Test 2**

|   Find Exact	|Find Closest   	| Total  	|
|---	|---	|---	|
| 0m 29s|  issue-stopped 	|	|

### Comments & Questions

1. Clearly, these identical results confirm those drawn earlier with [listFix()-2.8.1.2.](https://github.com/Borewit/listFix/pull/203#issuecomment-1734083904)

2. Support for #191 can also be fruitfully applied during test-runs, and not only during repair ops. Being able to switch media directories on and off, see extremely useful application.

3. Presumably, the search algorithm itself, has not yet been touched?

***

**Comment by Borewit** [comment]
> due to an issue that repeatedly broke the repair process. Namely, the repair process stopped immediately after having first completed finding the exact matches.

So sorry, made a mistake in the cancellation logic. I took it out, as it not necessary check with within processing a single playlist entry, per playlist entry is good enough. 

I overwrote the last commit, hence you get again a build with the same version number.

**Comment by touwys** [comment]
> [Build run (#6316151411, attempt #1) artifacts](https://github.com/Borewit/listFix/actions/runs/6316151411/attempts/1#artifacts)

Do you want me to repeat the ancient of speed test with build? Anything else perhaps, that I should check for? Can do it Wed. 27th.

**Comment by Borewit** [comment]
> > [Build run (#6316151411, attempt #1) artifacts](https://github.com/Borewit/listFix/actions/runs/6316151411/attempts/1#artifacts)
> 
> Do you want me to repeat the ancient of speed test with build? Anything else perhaps, that I should check for?

I would be interesting to know the difference in performance between the previous optimization and this one.
As that is the effective change of this PR.

The build reflect the state before this PR can be found here: https://github.com/Borewit/listFix/actions/runs/6302944637 

Please note that in the log file you can find the time it took to process the resolve the closest matches, e.g.: _Resolved closest matches in 38 ms_.

But it way more important that I did not break anything!

**Comment by touwys** [comment]
I can do this tomorrow, no problem at all. Is it alright if I go back and forth between the two builds, when installing the one over the other all the time?

**Comment by touwys** [comment]
> Please note that in the log file you can find the time it took to process the resolve the closest matches, e.g.: Resolved closest matches in 38 ms.

Thanks, and there I was using a stopwatch all this time. 😆

**Comment by Borewit** [comment]
> Thanks, and there I was using an stopwatch all this time. 😆

I admire your commitment!

**Comment by touwys** [comment]
> I admire your commitment!

It's mutual. 👍🏻

**Comment by touwys** [comment]
> Please note that in the log file you can find the time it took to process the resolve the closest matches [...]

@Borewit : I'm unable to locate those "logfile.log" files again... did the name, or location, perhaps change at all? Not desperately searching for it, though, as I'm able to carry on as before without it.

**Comment by touwys** [comment]
> Build run (#6316151411, attempt #1) artifacts

@Borewit : There appears to be an issue with the package installer for this build. When the installation is executed, there is a momentary flash of a process-dialogue across the screen, but the installation nothing carry on to complete:

***

[Screen Video](https://github.com/Borewit/listFix/assets/65730626/4f630fec-597a-4e1e-908b-52d3de3b3bc0)

**Comment by Borewit** [comment]
>  I'm unable to locate those "logfile.log" files again... did the name, or location, perhaps change at all?

No change, should be in: `%USERPROFILE%\.listFix()\logs`, e.g. `C:\Users\touwys\.listFix()\logs`

I will add a section to the [README to cover that](https://github.com/Borewit/listFix#file-locations).

**Comment by Borewit** [comment]
> There appears to be an issue with the package installer for this build. When the installation is executed, there is a momentary flash of a process-dialogue across the screen, but the installation nothing carry on to complete:

I don't think it is the build. It works for me, and we are building the deployment in the pipeline which gives a very consistent result. Try to uninstall, restart computer. On the quality of the installer itself I have very little influence.
 
Update: but I did have similar issue testing a different deployment with the same version number. Let me investigate if that can be improved.

**Comment by touwys** [comment]
> Try to uninstall, restart computer. On the quality of the installer itself I have very little influence.

Thanks, I was on the verge of doing just that, when a scheduled power blackout hit. 

> Update: but I did have similar issue testing a different deployment with the same version number. Let me investigate if that can be improved.

Will try again tomorrow after receiving the results of your investigation.

**Comment by Borewit** [comment]
For me uninstalling ListFix() was enough.

I also just merged #210 which an update of a component which has some influence on the build process.

**Comment by touwys** [comment]
> No change, should be in: `%USERPROFILE%\.listFix()\logs`, e.g. `C:\Users\touwys\.listFix()\logs`

Thanks, I was peeking in the wrong directory i.e. %appdata%. However, using the stopwatch is fun!

**Comment by touwys** [comment]
> For me uninstalling ListFix() was enough.

I will do that next when I'm at the PC then, and not wait for the outcome of your checking over of the build/installer. I was not too surprised at the trouble during the installation, because I've observed in the past that Windows does not like the crisscross installation of older and newer app versions.

**Comment by touwys** [comment]
@Borewit 

> I will do that next when I'm at the PC then, and not wait for the outcome of your checking over of the build/installer. I was not too surprised at the trouble during the installation, because I've observed in the past that Windows does not like the crisscross installation of older and newer app versions.

**2023.09.28**

_This installation failed, too. Same symptoms. The following measures were taken before attempting the installation this time:_

1. Downloaded the build anew, at: [Remove the "ancient PC" optimization · Borewit/listFix@b10ea22](https://github.com/Borewit/listFix/actions/runs/6316151411/attempts/1#artifacts).

2. Removed all traces of the previous test-build, namely that of listFix-2.8.1-4, from the Windows 7 PC.

3. Rebooted PC.

4. Executed listFix()-2.8.1-5 package installer.


***

**Comment by touwys** [comment]
@Borewit 

> [Build run (#6384221479, attempt #1) artifacts](https://github.com/Borewit/listFix/actions/runs/6384221479/attempts/1#artifacts)

Not sure whether I was supposed to download this **build listFix()-2.8.1.8**, but I did, and these are the results:

1. The Windows-installer for this build worked just fine.

### Results

**Test 1: listFix()-2.8.1-4**

| Media|   Find Exact	|Find Closest   	| Total  	|
|---	|---	|---	|---	|
|mp3+flac|   	1m 8s| 3m 44s	|   	4m 52s|
|mp3|   	29s| 1m 58s |2m 28s|

**Test 2: listFix()-2.8.1-8**

| Media|   Find Exact	|Find Closest   	| Total  	|
|---	|---	|---	|---	|
|mp3+flac|   	1m 9s| 3m 43s	|   	4m 52s|
|mp3|   	30s| 1m 58s |2m 28s|

### Comments

1. Results were virtually identical for these two builds. 

2. Stopwatch used. The given figures are rounded to next highest second.

***

### Additional Information:

1. As far as the _json-files_ are concerned — when they were opened after the test run:

  1.1 "history" — content:   

image

  1.2 "medialibrary" — not seen, notepad hung. 

  1.3 "options" — content
   
image


**2. Another strange issue is observable while re-adding a directory to the Media Directories pane:**

Steps:

2.1 Add a mp3 and afterwards a flac directory to the Media Directories pane.
2.2 Remove the mp3 directory.
2.3 Now, add the mp3 directory back, and, repeatedly, the flac directory gets displayed instead of flac, in the progress pop-up. (Screenshot below.)

image

***

**Comment by Borewit** [comment]
Thanks for test @touwys, seems that we can safely merge this simplified code.

I opened #215 to follow up the deprecated `playlistDirectory` option.

**Pull request merged**
