### PR TITLE
Eliminate `com.jidesoft:jide-components` dependency

### LINKED ISSUE #50: Eliminate JIDE Software dependencies

### PR DESCRIPTION
**Pull request by Borewit**
Eliminate [`com.jidesoft:jide-components`](https://mvnrepository.com/artifact/com.jidesoft/jide-components) dependency, aiming to be 100% open source.

Resolves #50.

ToDo:
- [x] Make tabs close-able

Test notes: The only thing which are relevant in this PR is the GUI.

### CODE REVIEW

**Comment by Borewit** [comment]
Build: [listFix_2.5.1-[PR51]-3.exe](https://www.mediafire.com/file/iad4z9tifo6dz7o/listFix_2.5.1-%255BPR51%255D-3.exe/file).

Known issue: tabs are not close-able, workaround: close via JMenu.

**Comment by Borewit** [comment]
Made the tabs close-able. Build: [listFix_2.5.1-[PR51]-4.exe](https://www.mediafire.com/file/svdnfob2igkd1zx/listFix_2.5.1-%255BPR51%255D-4.exe/file).

**Comment by touwys** [comment]
@Borewit 

Do you want listFix_2.5.1-[PR51]-4.exe tested, or [listFix_2.5.1-16](https://github.com/Borewit/listFix/pull/47#issuecomment-1414273756) ?

**Comment by Borewit** [comment]
If possible both. They both contain different changes. This is a different branch. Currently The trunk (default branch) of the tree is version 2.5.1. This PR describes the changes of this branch (relative to the trunk) which is about getting rid of commercial Jidesoft dependencies.

When you see no issues compared to 2.5.1, this one is going to be merged to the trunk (default branch). 

If you do, I keep adding commits (changes) to this branch to fix.

So this is the pattern we follow, it starts with an issue describing a specific change (bug/enhancement/debt/dependency-update). Then we create a branch to resolve that issue. When te branch is completed it will be pushed to GitHub and can then be turned into PR(pull request). Also called a change request. So this essentially a request (proposal) to change the trunk. Typically the PR describes the change, and also refers to the issue it claims to resolve.

**Comment by Borewit** [comment]
Build with improved playlist closure handling: [listFix_2.5.1-[PR51]-5.exe](https://www.mediafire.com/file/7hd5xkgtv16p52m/listFix_2.5.1-%255BPR51%255D-5.exe/file)

**Comment by touwys** [comment]
**listFix_2.5.1-[PR51]-4.exe**

I tested one playlist only. Same result as with [listFix_2.5.1-16:](https://github.com/Borewit/listFix/pull/47#issuecomment-1416779327):

Of the five closest matches found, three would play, and two would **not** [edit] react to input to play, at all.

•
[rollingfile.log](https://github.com/Borewit/listFix/files/10608960/rollingfile.log)
•

_Also, this build appears to have introduced a new issue, corrupted tab title-text:_

•
[Corrupted Tab Title Text](https://user-images.githubusercontent.com/65730626/216776084-4846fbfe-a9ea-4e2f-b79a-4515543d6d2a.png)
•

**Comment by Borewit** [comment]
> I tested one playlist only. Same result as with [listFix_2.5.1-16:](https://github.com/Borewit/listFix/pull/47#issuecomment-1416779327) Of the five closest matches found, three would play, and two would **not** [edit] react to input to play, at all.

So that must be an issue already present in [version 2.5.1](https://github.com/Borewit/listFix/releases/tag/v2.5.1) and should therefor best to be reported as a new issue/bug.

**Comment by Borewit** [comment]
> Also, this build appears to have introduced a new issue, corrupted tab title-text

I am so sorry, I cannot reproduce that issue, but I did find an issue closing tabs. I also tried different look & feels, but I had no issues in visualizing the tabs.

Latest build for this PR: [listFix_2.5.1-[PR51]-7.exe](https://www.mediafire.com/file/4nscjdew7cpqyxz/listFix_2.5.1-%255BPR51%255D-7.exe/file)

**Comment by touwys** [comment]
To be on the safe side, I'm going for a clean installation of listFix_2.5.1-[PR51]-7

**Comment by touwys** [comment]
> I am so sorry, I cannot reproduce that issue, but I did find an issue closing tabs. I also tried different look & feels, but I had no issues in visualizing the tabs.

I have just now installed listFix_2.5.1-[PR51]-7 — a clean installation:

1. Added Media Directory. _It loaded much, much quicker than before._

2. Opened Options and Set/Add Playlist Directory.

3. Opened the playlist to check Preview>Play. Quote:

> Of the five closest matches found, three would play, and two would **not** [edit] react to input to play, at all.

4. All five tracks now performed equally well.

5. The tab header-text is still corrupted, over here — even after the clean app installation, which reverted to the default font for the app. _[Edit: Also, I opened ca. 12 tabs in the tab bar, some of which were possible to close, and some did not]._

_Note 1 on 5: I reasoned that this text corruption issue might, perhaps, be related to the font style and size, so I wanted to test the theory by changing the font style and size in the app Options. To my surprise, the app hung after choosing the new font style, and had to be forcefully closed, before restarting._

_Note 2 on 5: The corrupted text, with the two exclamation marks, actually looks like two tabs superimposed one upon the other?_

_Note 3 on 5: Have you perhaps tried different font style? My usual default is Candara_14_

•
[rollingfile.log](https://github.com/Borewit/listFix/files/10609577/rollingfile.log)
•

**Comment by Borewit** [comment]
>  I opened ca. 12 tabs in the tab bar, some of which were possible to close, and some did not].

A yes, that issue I have as well, only the ~~last~~ active tab you are allowed to close 🤣

**Comment by Borewit** [comment]
Candara 14, changed that on the fly:
image

image

But I override the default tab visualization component, so I think for some reason on your end, the old one is also there. Let me try something...

**Comment by Borewit** [comment]
[listFix_2.5.1-[PR51]-9.exe](https://www.mediafire.com/file/1im96ignu2nms05/listFix_2.5.1-%255BPR51%255D-9.exe/file) fixing closing tabs, ~~and maybe the cluttered tab text~~?

**Comment by touwys** [comment]
**listFix_2.5.1-[PR51]-9**

Sorry for the delay. I was determined to find something sensible to report on. Hopefully, you will gain something worthwhile from the results below. The following is a reasonable, if not perfectly accurate, reflection of the steps that were followed in testing this build:

1. Tried installing and reinstalling listFix_2.5.1-[PR51]-9 several times, overwriting the previous installations. 

——_1.1 The issues, previously reported, persisted._

2. Prepared for a clean installation of listFix_2.5.1-[PR51]-9 by first removing completely all the files associated with the listFix installation. ("[Revo Uninstaller Pro](https://www.revouninstaller.com/)" was used for the job.)

——_2.1 The issues, previously reported, persisted._

3. Searched for possible leftovers, such as an app configuration file, that could possibly be susceptible to content corruption.

——_3.1 Discovered "C/Users/User/**.listFix()position.ini**". The uninstallers seems incapable of locating this file for removal._ 

4. Deleted ".listFix()position.ini", and installed listFix_2.5.1-[PR51]-9 anew.

5. Restarted the app, and set the Playlist and Media Directories.

——_5.1 This operation completed successfully._

6. Selected 12 x playlists from the Playlist Directory, and opened them all in tabs in the playlist edit pane.

——_6.1 [BINGO!](https://user-images.githubusercontent.com/65730626/216812115-f4545894-e179-4c2a-b741-735f29d62bba.png)_

——_6.2 Repair operations — "Find Exact Matches" & "Fix Everything" (i.e. "Find Closest Matches") — were initiated for two of the playlists. Both operations completed successfully. The Preview>Play operations also went well, and smoothly so._  

7. Opened "Options", and changed the font type, and size, twice before reverting to the default.

——_7.1 No issue found._

8. Closed several open playlist tabs by clicking on the blank space where the "x" used to be. (See 6.1)

——_8.1 I cannot rightly, or precisely, put my finger on it, but this process delivers "awkward" results, which are difficult to explain without further investigation._

9. Opened the app "File" menu, and selected "Close All" (Ctrl+Shift+W) with which to close all the open tabs at once.

——_9.1 All the tabs closed expediently and properly._

10. Selected again the same 12 playlists as before, to open for repairs. (See 6.0)

——_10.1 **Issue** reappeared: all the tab titles were now again corrupted._

11. Closed listFix.

12. Located and deleted the "C/Users/User/**.listFix()position.ini**" file.

13. Restarted listFix().

——_13.1 The closing configuration remained intact._ 
——_13.2 Where are the app config settings stored?_


•
PS. If already discarded, why should the "logfile.log" file still be present in the app logs? Also, in the "rollingfile.log" below, does not seem to contain any valuable information?
•
[rollingfile.log](https://github.com/Borewit/listFix/files/10610686/rollingfile.log)
•

**Comment by Borewit** [comment]
Thanks for you thorough review @touwys 

I don't believe much of the requirement to do deep clean. Uninstalling old Java versions, updating video drivers, although I don't think it will help, but have a higher probability to make a difference.

May I summarize your observations like this:

1. Opening 12 or more tabs may cause the close tab butting to vanish.
3. Awkward behavior closing tabs 
4. Opening and closing tabs after a while causes tab-component to render incorrectly, which may be relater to 3. 

> `.listFix()/position.ini` 

With the migration to from `.ini` files to `.json` I forgot the `position.ini`. I seems to used to open the playList() Window on the last position with the same size. Created issue #54 to migrate that one as well. In principal you should be able to delete those file and they will be re-generated.

> • PS. If already discarded, why should the "logfile.log" file still be present in the app logs? Also, in the "rollingfile.log" below, does not seem to contain any valuable information? • [rollingfile.log]

I agree, not relevant at this time. Only when you experience crashes or the application hangs. 

> 13.2 Where are the app config settings stored?

All application data is stored in `C:\Users\user\.listFix()\*`. You can open all files with a text editor.

Even if there some side-effects, **I am in favor of merging this PR** as having commercial software in here just no good. Even more I know now the added value was very limited. (I the process of removing, surprisingly I ended up with [more then 200 lines of code **less**](https://github.com/Borewit/listFix/pull/51/files)) . If required, I can remove the override of the tab visualization, and find an alternative way to close the tab.

**Comment by Borewit** [comment]
I cannot reproduce the issue, opened a large number of playlists, and closed all of those, and then opened then again, repeated that a few times, no side-effects:

image

**Comment by touwys** [comment]
> I cannot reproduce the issue, opened a large number of playlists, and closed all of those, and then opened then again, repeated that a few times, no side-effects:

We're missing something here. It seems like this issue is due to one or other file corruption. It does work properly with a clean installation, and that *.ini file removed. What causes this issue is yet to be established. It seems to be something that was introduced in later builds.

Just now, I deleted all the json settings files, restarted the app and set it up all over again. Then reopened the 12 playlists for repair, and yet their titles were still contaminated. It looks like two superimposed titles, as I explained before. 

What happened next, is surprising, I opened the Options dialogue, and tried to change the number of closest matches to find. The app immediately started to hang... I moved the indicator around... video:

•
[Tab Text Contaminated & App Hangs @ Options](https://user-images.githubusercontent.com/65730626/216819752-9619d474-35b3-47e9-92a7-1364e03aea89.gif)
•

**Comment by touwys** [comment]
> Even if there some side-effects, I am in favor of merging this PR as having commercial software in here just no good. Even more I know now the added value was very limited. (I the process of removing, surprisingly I ended up with [more then 200 lines of code less](https://github.com/Borewit/listFix/pull/51/files)) . If required, I can remove the override of the tab visualization, and find an alternative way to close the tab.

You have done very, very well so far, thank you. Follow your head, but just please don't give up now. I think if you can help sort out the contaminated tab-titles issue (your ref: "tab visualization"?) over here, we've got a nice workable app. Looking ahead, if you still feel up to it, there are still a handful of enhancement proposals waiting for you. These are not aimed at improving the current operations — because those really are fine — but more like to improve the work flow.

**Comment by Borewit** [comment]
I am not giving up.

Please note I created a new issue, with specific focus that problem @touwys, see #55.

This PR is now merged.

**Comment by touwys** [comment]
[THANK YOU](https://user-images.githubusercontent.com/65730626/216821417-ff5f51bd-88db-4d40-8cb0-aeeeabb56794.png)

_If you want to see one of my proposals in the meantime, where do you want me to put it for you?_

**Comment by Borewit** [comment]
> If you want to see one of my proposals in the meantime, where do you want me to put it for you?

Preferably in dedicated issues. That way I can follow up with focused PR's, and you focus on just testing on specific changes. 

PR #47 has now a lot of outstanding (refactoring) work, so if that PR does not introduce new issues, I like that very much to be merged.

**Pull request merged**
