### PR TITLE
Open file location of best match

### LINKED ISSUE #80: The "Open File Location" action is absent from the "Select Closest Matches" Dialogue
**listFix_2.5.1-19**

The "Open File Location" action is absent from the "Select Closest Matches" **Dialogue** box. Please add it to extend the Preview>Play review of the replacement track?

### PR DESCRIPTION
**Pull request by Borewit**
In the closest match search results, add a context menu to match results to open the file location of the best match

Resolves #80

### CODE REVIEW

**Comment by Borewit** [comment]
Build [listFix_2.6.0-[PR106]-5.exe](https://www.mediafire.com/file/z6tz2btm0m5yc3j/listFix_2.6.0-%255BPR106%255D-5.exe/file)

**Comment by touwys** [comment]
**listFix_2.6.0-[PR106]-5**

_Quickly tested only these functions:_

**Steps:**

1. Open a playlist in its PLE tab.

2. Select 11 broken tracks in the playlist presented.

3. Right-click, select "Find Closest Matches" from the context menu.

4. The "Select Closest Matches" dialogue opens, and presents the matching tracks it has found:

5. Click Preview / Play on any of the tracks. 

❌ _5.1 "Play" is now dysfunctional again — the tracks do not open in the default music player._

6.  Right-click on a track-title in Original Name column (in the "Select Closest Matches" dialogue), to activate "Open match file location":

❌ _6.1 This action found the locations for only 3 out of the 11 tracks tested. Thus, failed on 72%+_ 

ℹ️ _Please affirm_ that the action "Open match file location" (ref. 6), is designed to open the location of the matching track that is current in the "Matched Name" column. That is, it will locate the file location of each matched file, as it is being presented by working though the drop-down list. It is vital that it operates this way.

ℹ️ _Comment:_ As the work flow continues to improve, the lack of a visible link between the playlist active (i.e. currently selected) in the PLE and its counterpart displayed in the PLD, hinders. Hopefully, this does not present a major obstacle for you to fix?

•
[rollingfile.log](https://github.com/Borewit/listFix/files/10823508/rollingfile.log)
•

**Comment by Borewit** [comment]
>  5.1 "Play" is now dysfunctional again — the tracks do not open in the default music player.

I cannot reproduce that problem.

> 6.1 This action found the locations for only 3 out of the 11 tracks tested. Thus, failed on 72%+

I cannot reproduce that neither, I have tested a few playlists and they all repair just fine.

>ℹ️ Please affirm that the action "Open match file location" (ref. 6), is designed to open the location of the matching track that is current in the "Matched Name" column. That is, it will locate the file location of each matched file, as it is being presented by working though the drop-down list. It is vital that it operates this way.

I can confirm that I take new matched track (playlist item) location, from the current selected match.

> ℹ️ Comment: As the work flow continues to improve, the lack of a visible link between the playlist active (i.e. currently selected) in the PLE and its counterpart displayed in the PLD, hinders. Hopefully, this does not present a major obstacle for you to fix?

I did not bother me actually. I have similar layout for my development environment application, project files on the left side, tabs with files open on the right, and there is no synchronization in the selection among the two. But there is function to resolve the file I am editing in the file tree, which I use very frequently. Different issue though.

**Comment by touwys** [comment]
> I can confirm that I take new matched track (playlist item) location, from the current selected match.

So, just to be sure, when there are 10 matched tracks listed in the drop-down list next to the unmatched track, and then say unmatched track number 3 in the drop-down list is selected for the match, the location for unmatched track number 3 will have to open on demand?

> I did not bother me actually. I have similar layout for my development environment application, project files on the left side, tabs with files open on the right, and there is no synchronization in the selection among the two. 

I agree that it may not be essential to operations, but maintaining a synchronised link between the two certainly is reassuring. 

> I cannot reproduce that problem.

See: https://github.com/Borewit/listFix/pull/114#issuecomment-1445319342

**Comment by Borewit** [comment]
> So, just to be sure, when there are 10 matched tracks listed in the drop-down list next to the unmatched track, and then say unmatched track number 3 in the drop-down list is selected for the match, the location for unmatched track number 3 will have to open on demand?

I think I understand why you ask the question. If you select another track out of the suggested matches, it keeps opening the previous selected match. Only after you click outside the combobox (drop down for picking alternative matches), the selection get updated, and then it will open that file location. Is that it?

**Comment by touwys** [comment]
> I think I understand why you ask the question. If you select another track out of the suggested matches, it keeps opening the previous selected match. Only after you click outside the combobox (drop down for picking alternative matches), the selection get updated, and then it will open that file location. Is that it?

I'm using release listFix_2.6.0-PR114-5 where this function is no longer available. Hence, I can only confirm that _"If you select another track out of the suggested matches, it keeps opening the previous selected match"_. This part remains untested: _"Only after you click outside the combobox (drop down for picking alternative matches), the selection get updated, and then it will open that file location"._

What are the results at your end?

**Comment by Borewit** [comment]
I have now rebased this branch / PR. I have also fixed all of the [sonatype-lift](https://github.com/apps/sonatype-lift) bot recommendations. Do not expect much miracles to happen from the changes based on his suggestions. 

I still need to have a look if I can better handle the selection change.

Build: [listFix_2.6.0-PR106-9.exe](https://www.mediafire.com/file/efedyodlwowbqx4/listFix_2.6.0-PR106-9.exe/file)

**Comment by touwys** [comment]
> I have now rebased this branch / PR. I have also fixed all of the [sonatype-lift](https://github.com/apps/sonatype-lift) bot recommendations. Do not expect much miracles to happen from the changes based on his suggestions.
> 
> I still need to have a look if I can better handle the selection change.
> 
> Build: [listFix_2.6.0-PR106-9.exe](https://www.mediafire.com/file/efedyodlwowbqx4/listFix_2.6.0-PR106-9.exe/file)

I am onto it. In my book, the opening of matched file locations is an essential operation. 

The [sonatype-lift](https://github.com/apps/sonatype-lift) bot recommendations are out of my field of play. 👽

**Comment by touwys** [comment]
**Test Results for listFix_2.6.0-PR106-9**

_Steps:_

**1.** Open 3 playlists, from various sources, in the PLE.

**2.** `Open File / Options / Theme` and change default to "Darkstar".

**2.1** _The 3 playlist tab-titles disappear._

**2.2** _Change the Theme back to the default, and the tab-titles are still blank._

**3.** `Select Closest Matches` dialogue activated to test `Open File Location`:

**3.1** _More often than not, the explorer window that opens to the selected match, — that is, any match selected from the matches presented in the drop-down list — **opens and shuts instantly**. Repeating the exercise, with the same match, subsequently opens the correct location._

**3.2** _The matched file, **once located**, is **inconsistently highlighted** for easy identification amongst the other files. More often than not, the located file is not getting highlighted at all._

___

❓ Why is the action `Open File Location`, in the `Select Closest Matches` dialogue, not performed by right-clicking on the most current match in the drop-down list of matched files, in the `Matched Name` column? This certainly is the most sensible, intuitive place, to look for it to perform the operation. Instead, it is performed by right-clicking on the `Original Name` for which the file supposedly does not even exist.

___

**Comment by Borewit** [comment]
> ❓ Why is the action Open File Location, in the Select Closest Matches dialogue, not performed by right-clicking on the most current match in the drop-down list of matched files, in the Matched Name column? This certainly is the most sensible, intuitive place, to look for it to perform the operation. Instead, it is performed by right-clicking on the Original Name for which the file supposedly does not even exist.

No it was not using the original filename, but their was weird propagation from the selection, causing the accessible selection to be kind of step behind. I made that more direct, and the context menu will be triggered from the combo-box as well: [listFix_2.6.0-PR106-11.exe](https://www.mediafire.com/file/9iv5extohnxdiky/listFix_2.6.0-PR106-11.exe/file)

**Comment by touwys** [comment]
> No it was not using the original filename, but their was weird propagation from the selection, causing the accessible selection to be kind of step behind. I made that more direct, and the context menu will be triggered from the combo-box as well: [listFix_2.6.0-PR106-11.exe](https://www.mediafire.com/file/9iv5extohnxdiky/listFix_2.6.0-PR106-11.exe/file)

👍🏻 OK, thanks for explaining that.

**Comment by touwys** [comment]
**Test Results: listFix_2.6.0-PR106-11**

**1.** Changing the theme at `File / Options / Theme` clears the tab-titles of all the playlists opened in the Editor.

**1.1** _Closing all tabs, and resetting the theme to default, and opening the tabs again, will restore the tab-titles that were previously cleared upon changing the theme. Repeating the process, will often hang the programme, which then has to be closed, forcefully._

**2.** Still clicking on the title of the unmatched track located under the `Original Name` column, in order to locate the matched track located right next to it in the `Matched Name` column, drop-down list.

**2.1** _Working down the list of unmatched tracks in the `Original Name` column, one at a time, they all presented **exactly the same matched track location** for each one._ 

____

ℹ️ The drag and drop of playlists from the PLD onto PLE, is a very nice touch, which I have not noticed before. Great idea! 

❓ Going back several preceding releases, the PR number has been dropped from the start-up & name tag? The PR- indication helps to keep perspectives relative while testing.
____

•
**[rollingfile.log](https://github.com/Borewit/listFix/files/10848665/rollingfile.log)**
•

**Comment by touwys** [comment]
@Borewit:

Please check the preceding post. Log-file now added, which I forgot. 😌

**Comment by Borewit** [comment]
>  Changing the theme at File / Options / Theme clears the tab-titles of all the playlists opened in the Editor.

Please report is a new issue as I don't think it is introduced with this PR.

> Closing all tabs, and resetting the theme to default, and opening the tabs again, will restore the tab-titles that were previously cleared upon changing the theme. Repeating the process, will often hang the program, which then has to be closed, forcefully.

New issue

> 2. Still clicking on the title of the unmatched track located under the Original Name column, in order to locate the matched track located right next to it in the Matched Name column, drop-down list.

> 2.1 Working down the list of unmatched tracks in the Original Name column, one at a time, they all presented exactly the same matched track location for each one.

Yes, it opens the location of the current selected match, anywhere on that row. That's what it also says in the context menu "Open match file location". 

Selecting one of the alternative location is tricky, as they appear somewhere in the drop down, then on top that floating drop down I would have show another floating context menu. If you want to know the file location of the alternative, there is already the tooltip.

>  Going back several preceding releases, the PR number has been dropped from the start-up & name tag? The PR- indication helps to keep perspectives relative while testing.

The version is now totally dynamically being added. The version is not aware on which branch it is. I can add the commit hash, to make it unique. Adding the PR's to the installations I do by hand.

Latest build of this PR, rebased on other merged ~~PR: [listFix_2.6.0-PR106-16](https://www.mediafire.com/file/4uvsvwmgzif42i3/listFix_2.6.0-PR106-16.exe/file)~~

I propose to do a regression test after you approve this PR. Aiming to nail problems already merged into the default branch. So aiming for any kind of bugs.

**Update: this introduced a bug**

**Comment by touwys** [comment]
> Yes, it opens the location of the current selected match, anywhere on that row. That's what it also says in the context menu "Open match file location".

I think we have a misunderstanding here? Let's say there are three unmatched tracks listed in the `Original Name` column, called —

_Track One
Track Two
Track Three_

Each one of the aforesaid, has 10 matched tracks listed in the relevant drop-down box situated next to it in the `Matched Name` column.

1. Call the context menu for _Track One_ and select `Open match file location` for the very first match presented next door in the drop-down list.

1.1 This opens _Location A_

2. Select the _next_ matched track in the drop-down list for _Track One._

2.1 This opens _Location A_

2.2 Thus, the same location repeats for all the matched track in the drop-down list.

3. Call the context menu for _Track Two_ and select `Open match file location` for the very first match presented next door in the drop-down list.

3.1 This opens _Location A_

4. Select the _next_ matched track in the drop-down list for _Track Two._

4.1 This opens _Location A_

...and so forth. So whatever match gets selected, each one of them, irrespective of which unmatched track is selected, will call exactly the same location. i.e. _Location A._

___

**Comment by Borewit** [comment]
Ah yes, I see what you mean, it still doesn't update to the last selection. Still some work to do.

**Comment by touwys** [comment]
**Testing listFix_2.6.0-PR106-16**

I had a quick run with this build before the power grid went down again:

After a clean install, the Media Directory was added, immediately followed by dragging and dropping two playlist folders to the PLD. The very next step was to open a playlist via the File Context Menu, from the media library, directly into the PLE. 

This caused listFix to hang (@ screenshot), so that it had to closed forcefully, again.

Observation: _The most likely cause for this is that the playlist I was trying to open, was pre-existing in one of the PLD-folders. If so, it has to be safeguarded against._

Sorry, no log file yet. 😢 

Screenshot_20230228 _ listfix playlist hangs

**Comment by midmarch** [comment]
> Testing listFix_2.6.0-PR106-16

That release got some nasty bugs, sorry about that. Made a few typo's in button image references, introduced in #121.

**Comment by Borewit** [comment]
That release got some nasty bugs, sorry about that. Made a few typo's in button image references, introduced in https://github.com/Borewit/listFix/pull/121.
No need for a log file.

**Comment by touwys** [comment]
> That release got some nasty bugs, sorry about that. Made a few typo's in button image references, introduced in #121. No need for a log file.

No problem. Upon restart, I can confirm that opening a playlist from anywhere, causes the app to hang. So my preceding comment is not valid.

**Comment by Borewit** [comment]
This one should have the correct selected match location right: ~~[listFix_2.6.0-PR116-17.exe](https://www.mediafire.com/file/pty10gzcn7qyu08/listFix_2.6.0-PR116-17.exe/file)~~ [listFix_2.6.0-PR106-17.exe](https://www.mediafire.com/file/jdgddh7lp2jv8no/listFix_2.6.0-PR106-17.exe/file)

**Comment by touwys** [comment]
> This one should have the correct selected match location right: [listFix_2.6.0-PR116-17.exe](https://www.mediafire.com/file/pty10gzcn7qyu08/listFix_2.6.0-PR116-17.exe/file)

Thank you, I envisage testing the aforesaid PR, today. Have uploaded **[this schedule ](https://workupload.com/archive/CBMcWZHp)** for you to take a peek at.

👉🏻 **Update:** _The release is unavailable at the link provided?_

**Comment by Borewit** [comment]
Ah crap, correction: [listFix_2.6.0-PR106-17.exe](https://www.mediafire.com/file/jdgddh7lp2jv8no/listFix_2.6.0-PR106-17.exe/file)

**Comment by touwys** [comment]
**Testing: listFix_2.6.0-PR106-17**

✔️ **The fix is in for Open match file location.**

____

_The following are additional points of observation — some of which have previously popped up. Please indicate which of these you wish to have posted under issues:_ 

1. The tab-labels still go blank, once the theme is changed at `File / Options / Theme. However, I am unsure if that is the sole cause — there might be other reasons left to discover? 

2. Changing the theme may also cause the app to hang. After the restart, the newly chosen theme is active, and opening the same playlists tabs in the PLE, the tab-titles return.

3. If all the playlist-tabs with blank titles are closed simultaneously (Ctrl+Shift+W), and the same playlists are then reopened, the tab-titles text return.

4. Sometimes, changing the font style will cause the app to hang.

5.  Darkstar Theme > `Select Closest Matches` dialogue > `Matched Name` dropdown box:  Issue — matched tracks text are _unreadable_.
 
6. `Select Closest Matches` dialogue: Issue with the size of the PLAY-tab buttons in the `Preview / PLAY` column. The buttons become all squeezed together with Font-style changes.

____

❓ How does listFix() search for a matched track — by music file tags, or the file description?

____

@Borewit: Here is the log: 🤕 

[rollingfile.log](https://github.com/Borewit/listFix/files/10870744/rollingfile.log)

____

**Comment by Borewit** [comment]
> question How does listFix() search for a matched track — by music file tags, or the file description?

For sure not using metadata tags. There is no functionality present in listFix() software to extract audio tags. In the dependent library [lizzy](https://github.com/Borewit/lizzy), which is the other project I adapted to eliminate all vague non open source dependencies used.

[lizzy](https://github.com/Borewit/lizzy) actually is, sort of able to read tags, relying on some a [ffmpeg Java component](https://sourceforge.net/p/lizzy/code/HEAD/tree/trunk/ext/ffmpeg/) which is relying on a native (non-Java) [ffmpeg](https://ffmpeg.org/) installation. Yet that whole ffmpeg part is excluded from this dsitribution.

The "closest match" is purely based on the filename portion of the audio track, so excluding the parent folder.

https://github.com/Borewit/listFix/blob/a452d74c0cab53ef7f3ea2a42b3185c3e84b59d4/src/main/java/listfix/util/FileNameTokenizer.java#L30-L33

This score function is chopping the file name into words, e.g.: `"01 Madonna - Like a Prayer.mp3"` becomes something like: `["01", "Madonna" , "Like", "Prayer"]`.

`scoreMatchingTokens` function is then comparing these words, in each track in your library, also converted to a similar list of words. Then a score is basically calculated comparing those sets of words.


> 1.  The tab-labels still go blank, once the theme is changed at `File / Options / Theme. However, I am unsure if that is the sole cause — there might be other reasons left to discover?
> 2. Changing the theme may also cause the app to hang. After the restart, the newly chosen theme is active, and opening the same playlists tabs in the PLE, the tab-titles return.
> 3. If all the playlist-tabs with blank titles are closed simultaneously (Ctrl+Shift+W), and the same playlists are then reopened, the tab-titles text return.
> 4. Sometimes, changing the font style will cause the app to hang.

I suggest to combine those in one new issue

> Darkstar Theme > Select Closest Matches dialogue > Matched Name dropdown box: Issue — matched tracks text are unreadable.

I noticed that. Not sure where that is coming from. If it the a Java theme which is essentially just shit, I am not very motivated to repair it. Then rather disable the most problematic themes The GUI also looks totally different on Linux (at least with some themes), so it very sensitive for the OS flavor it is running on. 

Investigating to port the entire GUI to a more modern alternative like (https://openjfx.io/)[https://openjfx.io/]. But this is a massive effort. 

But you can always capture your wishes in issues. Java GUI's not my biggest strength, maybe some other developers wants to contribute, although I this very project very little probability to be picked as the user community is very tiny.

**Comment by touwys** [comment]
> 5\. Darkstar Theme > `Select Closest Matches` dialogue > `Matched Name` dropdown box:  Issue — matched tracks text are _unreadable_.

Thank you for your dedication, comments, and answers to my questions. 

Before I go ahead to respond more fully to the aforesaid point you have made, I wish to discuss something with you —

Simply put, I agree with you that fixing some of the issues related the GUI -- such as the one with the Darkstar theme, which is quoted above — is not really worth the effort. ListFix() is a tool, not a fanfare. Therefore, I suggest that you drop all the current themes from Options. Simply stick to the default. You can streamline the default theme to your heart's content as, and when, the need arises. With only one theme to work with, it will allow you to focus on fine-tuning the operational side of things. That is what a good tool is designed for, and what it should do, precisely. My guess is that quite a few issues could disappear along with the superfluous themes. 

____

**Pull request merged**
