### PR TITLE
Improve cancellation behavior in fix playlist  dialogs

### PR DESCRIPTION
**Pull request by Borewit**
Prevent repair job from keep running when user cancels at the repair stage.

### CODE REVIEW

**Comment by Borewit** [comment]
Are you able to review this PR @touwys?

Corresponding [Windows build](https://github.com/Borewit/listFix/suites/16254958532/artifacts/928174943).

**Comment by touwys** [comment]
### listFix 2.8.0_7 — Ref Issue #194 — Review ###

The issue persists. After having saved, the first round of (exact) repairs, and going to track number 1 which still needs to be matched:

1. Select track 1.
2. Right-click for its context menu to open.
3. Select "Repair playlist" 
4. Select the match, and click OK to return to the list still open in the editor. (Note: In this particular instance, only one match was found).
5. Track number 1 is correctly replaced with the match found.
6. Repeat Steps 1-4 above, for the next track in line to find a match for. (Let's say this track is number 7)
7. **Track 1 is now discarded, and gets replaced with track 7.**
8. This issue repeats whenever steps 1-4 above are repeated with other tracks, which require matches: Each time, Track 1 will get replaced with the newer match.

Note: This issue could probably be related to issue https://github.com/Borewit/listFix/issues/196

**Comment by Borewit** [comment]
> ### listFix 2.8.0_7 — Ref Issue #194 — Review
> The issue persists. After having saved, the first round of (exact) repairs, and going to track number 1 which still needs to be matched:
> 
> 1. Select track 1.
> 2. Right-click for its context menu to open.
> 3. Select "Repair playlist"
> 4. Select the match, and click OK to return to the list still open in the editor. (Note: In this particular instance, only one match was found).
> 5. Track number 1 is correctly replaced with the match found.
> 6. Repeat Steps 1-4 above, for the next track in line to find a match for. (Let's say this track is number 7)
> 7. **Track 1 is now discarded, and gets replaced with track 7.**
> 8. This issue repeats whenever steps 1-4 above are repeated with other tracks, which require matches: Each time, Track 1 will get replaced with the newer match.
> 
> Note: This issue could probably be related to issue #196

This PR only address step 2 of issue #194, to actually cancel the job. It indeed does not resolve other behavior described in #194.

**Comment by touwys** [comment]
### listFix 2.8.0_7 — Ref Issue https://github.com/Borewit/listFix/issues/194 — Review _Revised_ ###

> Resolves behavior described in issue #194, step 2:
> 
> > Immediately, after having it detect all the exact matches, cancel the "Select Closest Matches" dialogue still in progress. Accordingly, it should not proceed with next trying to detect the closest matches.

Can confirm that the above issue has been taken care of with this release.

Thank you.

**Pull request merged**
