### PR TITLE
Build Windows installers with jpackage

### PR DESCRIPTION
**Pull request by Borewit**
1. Build `.msi` & `.exe`, with jpackage,  and add these artifacts to the build pipeline
2. Remove the previous jlink runtime image artifact from the pipeline
3. Disabled the (DOS) console, (uses javaw instead of java)

Related to #164 

<a href="https://github.com/Borewit/listFix/actions/runs/4774069199/attempts/1#artifacts" title="Optional link title">
  indows installers</a>

### CODE REVIEW

**Comment by Borewit** [comment]
@touwys, can you to try the new Windows installer(s)?

**Comment by touwys** [comment]
> @touwys, can you to try the new Windows installer(s)?

Installed via the MSI to the default directory, `C:\Users\*\AppData\Local`

_The installation was problem-free, and the app also started without any apparent issues._

**Comment by Borewit** [comment]
> > @touwys, can you to try the new Windows installer(s)?
> 
> Installed via the MSI to the default directory, `C:\Users\*\AppData\Local`

I was a bit surprised by that as well, seems to be an individual installation rather then a shared installation.
Need to check if I can customize that.
 
> 
> _The installation was problem-free, and the app also started without any apparent issues._

Version is missing in application window title:

image

Also the application is listed as "listfix" instead of "lisFix()".

image

**Comment by touwys** [comment]
> Version is missing in application window title:

Yes, I had already provided a screenshot of this incidence for another, recent distribution, which I am unable to track now. Should I, forthwith, peg down errors repeated in subsequent releases, everytime it is noticed? Is not once logged, sufficient?


____

> Also the application is listed as "listfix" instead of "lisFix()".

Sorry, I missed this one, and cannot check the location of the error right now. Please note the spelling error at the end of the sentence above, in case you are copying and pasting it:

"lisFix()" should read "listFix()". The "t" is missing.

----------------------------------------

23 Apr 2023 16:43:38 Borewit ***@***.***>:

**Comment by Borewit** [comment]
>  Is not once logged, sufficient?

In principal that is sufficient. I think this one is introduced in #164, which is kind of the groundwork for this PR, therefor I will address in this PR. I remember you have reported it before, but I think that was based on a screenshot I provided, running it in dev environment, but I could be wrong. Doesn't matter.

**Comment by touwys** [comment]
@Borewit 

**"Save Playlist Error"**

I am logging this build-error here, instead "Issues":

Unfortunately, I did not keep track of the steps that have led up to this error, but I did take the screenshot below. Does it help any?

**[Playlist Saving Error _ Screenshot 20230425](https://user-images.githubusercontent.com/65730626/234219420-e3b0732b-7e39-4d14-b5db-99ac2359f15c.png)**

•••••••

**Comment by Borewit** [comment]
Can you try this this PR again @touwys?

- I think I resolved the "Save Playlist Error" via #170, which now included here as well.
- Name corrected
- windows update GUI added, which correlate updates (best to de-install previous version)
- Fixed version number

**Comment by Borewit** [comment]
Build: [Windows](https://github.com/Borewit/listFix/suites/12569660819/artifacts/672006263)

**Comment by touwys** [comment]
**listFix_2.7.0-11:**

> I think I resolved the "Save Playlist Error" via Fix uncommon root exception #170, which now included here as well. ❔ 

I could not reconstruct this error, confidently. Because, originally, it was induced purely by accident. Were you able to reconstruct the exact steps from the error report submitted? 

> Name corrected. ✔️ 

> windows update GUI added, which correlate updates (best to de-install previous version) ✔️ 

No issues here. It lands on this page proper: [Releases · Borewit/listFix](https://github.com/Borewit/listFix/releases)

>Fixed version number ✔️ 

______________

Below there are screenshots, some annotated, that graphically display some of the immediate results. _I propose that the start-up splash screen gets modified to something similar to the one shown:_

•
Default install directory:
20230501_installs to appdata local
•
Current splash screen:
20230501_splash screen at startup
•
Proposed splash screen:
20230501_splash screen at startup_revised
•
Playlist tab not refreshing, invariably.
20230501_playlist tab not refreshing one playlist changes are discarded
•

**Comment by touwys** [comment]
@Borewit :
In the case of listFix(), how are the graphical elements incorporated into the software? Are these elements — for example the start-up splash screen — designed in another programme, ready to be imported for assimilation in the listFix() development package?

**Comment by Borewit** [comment]
> @Borewit : In the case of listFix(), how are the graphical elements incorporated into the software? Are these elements — for example the start-up splash screen — designed in another programme, ready to be imported for assimilation in the listFix() development package?

I reversed engineered the original splash screen to SVG which can be found [here](https://github.com/Borewit/listFix/blob/main/src/main/svg/listFix()%20logo.svg). 

One of the apps able to edit SVG is [inkscape](https://inkscape.org/), or a text editor is enough to change a position.

Note that the fourth digit group (.11) is the commit distance from the last release, that one will not be present the real release.

**Comment by Borewit** [comment]
> I could not reconstruct this error, confidently. Because, originally, it was induced purely by accident. Were you able to reconstruct the exact steps from the error report submitted?

No, but based on the error I think this is caused when the paylist is one drive, and at least one track on another drive. Then enable the relative path, and that is probably the way to reproduce it.

**Comment by Borewit** [comment]
> Playlist tab not refreshing, invariably.

I think the Playlist tab not introduced in this PR, so I guess best to create a new issue for that.

**Comment by touwys** [comment]
> I reversed engineered the original splash screen to SVG which can be found here.

What about any of the other GUI elements contained in the app — are there elements other than the splash-screen that may need an update/redesign from time-to-time? If here are, I would like to offer to help you with that, as far as I am able to. Also, is it imperative that _all_ such images be presented in the SVG-format? 

> Note that the fourth digit group (.11) is the commit distance from the last release, that one will not be present the real release.

Yes, I am aware of that, but I submit that the centralised version number is _more versatile_ and neater.

**Comment by Borewit** [comment]
> Also, is it imperative that all such images be presented in the SVG-format?

SVG is the best foundation to store graphics. As it is commonly used, vector based (scale-able without loss of quality), it is code (text)  (works well with repo and it allows to manipulate text). For some type of graphics is less suitable.

I did some experiments with regenerating buttons, but I though the result of that was fairly disappointing. It looks like the Java Swing GUI as good in rendering graphics as browsers are nowadays. Buttons looked very pixelated.  Maybe that gets better switching to JavaFx.

**Pull request merged**
