### PR TITLE
Add Playlists Editor border

### LINKED ISSUE #66: Add On the Name: Playlist Editor
Add on a name for the window pane into which the playlists are getting opened in their tabs for repairs and editing:

•
Playlist Editor
•

### PR DESCRIPTION
**Pull request by Borewit**
Resolves #66

### CODE REVIEW

**Comment by Borewit** [comment]
Build [listFix_2.7.0-PR158-2.exe](https://workupload.com/file/Fn4z9ehKMeb)

**Comment by touwys** [comment]
**Review: listFix_2.7.0-PR158-2**

1. New panel description "Playlist Editors" is added. 

2. I propose that the description "Playlist Editors" be revised to "Playlists Editor".

3. There is an observable shift in the graphics scaling, again, with this build. Any idea why, after the perfect display previously? The same settings were used. Theme — Nimbus and Font Style — Candara_14.

**Comment by Borewit** [comment]
Do you mind to try this distribution @touwys:? 
[listFix-2.7.0-6.zip](https://github.com/Borewit/listFix/files/11162348/listFix-2.7.0-6.zip)

You need to unzip it somewhere, and run `\listFix-2.7.0-6\bin\listFix.bat`.
To get rid of it, just delete the unzipped folder.

**Comment by touwys** [comment]
> To get rid of it, just delete the unzipped folder.

Sure, I've downloaded it moments ago. Relatively speaking, it is a very small file, and is it a _portable version_?

**Comment by touwys** [comment]
@Borewit 

Which executable do I run? — **listFix-2.7.0-6.jar**?

**Comment by Borewit** [comment]
> Which executable do I run? — **listFix-2.7.0-6.jar**?

`\listFix-2.7.0-6\bin\listFix.bat`

> Relatively speaking, it is a very small file, and is it a portable version?

If that means, there is no installer and you unzip and run it, the answer is yes.
It's the out-of-the box compiling / assembling of a Java 11+ application. 

With this way of compiling, only parts of the JRE wich are required are "linked" in.
The way we build the installers is using a more old fashion which wraps the entire JRE. 

What is not possible out-of-the-box, is make one nice .exe of it with an icon. This poor Windows integration is big big mistake Java is keep making since it was invented. 

I am looking for a way to use this distribution, but there is so little documented how to this properly. You need all kinds of complex third party tools.

**Comment by touwys** [comment]
> \listFix-2.7.0-6\bin\listFix.bat

I did run the bat-file already. What I meant is, what do I run next after the bat-file — I thought that would be listFix-2.7.0-6.jar?

**Comment by touwys** [comment]
@Borewit, I don't know about the Java-stuff. I had guessed to run listFix-2.7.0-6.jar, from what I could remember from the old Java-app. Remember, I'm a rookie. 🙃

**Comment by Borewit** [comment]
> @Borewit, I don't know about the Java-stuff. I had guessed to run listFix-2.7.0-6.jar, from what I could remember from the old Java-app. Remember, I'm a rookie. 🙃

The .bat file should start the application. If that doesn't happen something is wrong. On my machine it works. Indeed, jar files can be made so you run them. Like this one: [listFix-2.7.0-6-all.jar.zip](https://github.com/Borewit/listFix/files/11173811/listFix-2.7.0-6-all.jar.zip). You need remove the .zip extension by renaming it, don't extract that one! I am not allowed upload jar here, that why I added `.zip`. In fact a jar is a zip file.

The jar distribution file linked to [v2.7.0](https://github.com/Borewit/listFix/releases/tag/v2.7.0)   works that way. Another portable distribution. So I can also send you test versions that way, if you prefer.

With support of a local JRE. The compiled version does not need a JRE, if works. You may see an error, if you first startup `cmd`, then run the .bat file. That way the error message does not immediately disappear.

**Comment by touwys** [comment]
> listFix-2.7.0-6-all.jar

> \listFix-2.7.0-6\bin\listFix.bat

When either one of the aforesaid is executed, JVM immediately flags the following Java-exception:

image

Could it be fixed at my end? Windows 7 x64 OS.

____

**Comment by Borewit** [comment]
> Could it be fixed at my end? Windows 7 x64 OS.

That is probable why the binary distribution does not work, as I have build it on Windows 11.

The `listFix-2.7.0-6-all.jar` should work with a JRE installed compatible with at least Java version 15.
Best to remove anything older then that, and switch to version 17 LTS (Long-term support):
For example this one: https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/downloads-list.html

More info about versions and links to various distribution here: https://whichjdk.com/

_Which one is the best?_ I have no idea, I am lost in Java releases, after Java 1.8 (compatibility version 8) things became very chaotic.

**Comment by midmarch** [comment]
@touwys. in this PR #160 I extended the build pipeline to automatically generate the "Fat-JAR" (executable Jar file). 

If you are able to run such file, each PR automatically has "portable" dsitribution attached which you can try and run/

**Comment by Borewit** [comment]
@touwys. in this PR https://github.com/Borewit/listFix/pull/160 I extended the build pipeline to automatically generate the "Fat-JAR" (executable Jar file).

If you are able to run such file, each PR automatically has "portable" dsitribution attached which you can try and run.

It is very well hidden (sorry, that is out my conrol), so added instruntions how to access it.

**Comment by touwys** [comment]
@Borewit:

My installed Java-version was updated recently, on January 23, 2023 — **version "jre1.8.0_361"**. I suppose it fails the compatabilty test?

**Comment by Borewit** [comment]
> @Borewit:
> 
> My installed Java-version was updated recently, on January 23, 2023 — **version "jre1.8.0_361"**. I suppose it fails the compatabilty test?

Indeed. That JRE 1.8 is a sort of dead end probably best to remove that software.

**Comment by touwys** [comment]
> Indeed. That JRE 1.8 is a sort of dead end probably best to remove that software.

Removed it, thank you, and looking forward to the next move.

**Comment by Borewit** [comment]
> > Indeed. That JRE 1.8 is a sort of dead end probably best to remove that software.
> 
> Removed it, thank you, and looking forward to the next move.

[Amazon Corretto 17 requires Windows 10](https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/windows-7-install.html)

It will be tough with Windows 7. Windows 7 reached it end of it's support in January 2020.  That means software vendors normally also drop their support.

Does the [Oracle SDK 17 work version work?](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe)

If not, maybe [Oracle SDK 15](https://www.oracle.com/java/technologies/javase/jdk15-archive-downloads.html#license-lightbox), which is just enough.

When I build an installer, it wraps the JRE, so there should be a binary complaint Windows 7 JRE, otherwise you would not be able to run listFix().

**Comment by touwys** [comment]
> It will be tough with Windows 7. Windows 7 reached it end of it's support in January 2020. That means software vendors normally also drop their support.

I am aware of that, but for various reasons, I am loath to upgrade. For instance, I use a huge number of apps tailored to suit Win 7, and some of these could stop working properly under a new OS. Windows 7's end of life was extended to 2023, already. Estimates for Windows 7 users vary from 100 million (min.) to 200 million [(probable)](https://tinyurl.com/3k5j5b44)., which is a considerable number. Hopefully, ideally, you can continue to accommodate Windows 7?

I am rather going to steer clear of the Java-options in order to avoid probable complications.

**Pull request merged**
