### PR TITLE
Fix repairing a selection of a playlist

### LINKED ISSUE #194: Anomaly: a manually repaired track, once saved, gets replaced by the next repair
**listFix() v2.8.0**

Location is the Playlist Editor, in which there is open a 24-track playlist. The 24 tracks are all up for repair (finding matches).

**Steps:**

1. Click the magic wand on the toolbar to start the auto repair for all of 24 tracks.

2. Immediately, after having it detect all the _exact_ matches, _cancel_ the "Select Closest Matches" dialogue still in progress. Accordingly, it should not proceed with next trying to detect the _closest matches_.

3. Click on the diskette button on the toolbar, in order to save this first round—the _exact_ repairs—to the playlist.

4. Next, select _one_ "file name" (i.e. track)—starting with the _first one_ in the playlist—for which a matching track is to be found. Right-click on it.

5. In the context menu presented, choose "Repair Playlist". 

6. Select "OK" for the first (any?) match found.

7. Upon return to the playlist, after clicking OK, save the playlist.

8. Select the _very next_ (any?) track in the playlist for which a matching track is to be found. Right-click on it.

9. In the context menu presented, choose "Repair Playlist". 

10. Select "OK" for the first (any?) match found.

11. Upon return to the playlist, after clicking OK, save the playlist.

**Issues:**

The track that got repaired first, and was saved, gets summarily replaced by the second track that got repaired. However, the second, _unrepaired_ track still also remains in position in the playlist, thus keeping the total number of tracks in the playlist at 24.

—

### LINKED ISSUE #196: Repairing a playlist misbehaves, replaces and duplicates selected matched tracks...
**listFix() v2.8.0**

The steps described here, were followed on a completely broken playlist containing 24 unmatched tracks. 

**Steps:**

1. Open the playlist needing repair from the Playlist Directories pane into the Playlist Editor, ready for editing.

2. Click the magic wand icon on the toolbar to initiate the auto repair function for all of 24 tracks.

3. Cancel the "Select Closest Matches" process dialogue _as soon as it has completed detecting the first batch of track matches._ (These will be the _exact_ track matches, each one marked by a green check mark/tick).

4. Click on the diskette icon on the toolbar to save the first round of track matches—the exact matches. (The green check marks, should now have changed into a green "OK" icon. Note, too, that after now having saved the playlist, the "Reload" icon on the toolbar is dulled.)

5. Select all the 13 unmatched tracks (indicated by a red & white exclamation marker to the right of the track number).

6. Right-click on the 13-track selection.

7. Select and initiate "Repair Playlist" on the context menu.

8. Allow the "Select Closest Matches" process to complete, and once the list of matched track are presented in the "Select Closest Matches" dialogue, immediately click "OK" to accept all the recommendations, just as they are presented.

9. Now, back in the Playlist Editor, notice the changes: There are green checkmarks next to 13 tracks, indicating they've been "repaired". **However, 5 tracks have _new_ (i.e. previously absent) red exclamation marks next to them.**

10. Press the diskette button on the toolbar to save the list as presented in step 9. The "OK" icon should appear next to the newly saved, 13 matched tracks.

11. Repeat steps 5-8 on the number of tracks shown in step 9 shown to display a new red exclamation mark next to it.

12. Again, back in the Playlist Editor, **notice these new changes**: There are green checkmarks next to the newly repaired tracks (5 in this instance) in the playlist, indicating they've been "repaired". **However, the 5 tracks that were repaired are duplicates of the 5 tracks, each of which still bears the _new_ red exclamation marks next to them.**

**Issue:**

1. Matched tracks are discarded, duplicated, etc, due to the malfunction/misbehaviour of the repair process under the circumstances describe. The issue is repeatable.

2. Probably related to [194#](https://github.com/Borewit/listFix/issues/194#issue-1822355050)

—

### PR DESCRIPTION
**Pull request by Borewit**
Fixes the repair process, on a selection of playlist entries.
Result what written at the wrong location within the playlist. 

Resolves: Borewit/listFix#194, Borewit/listFix#196

### CODE REVIEW

**Comment by Borewit** [comment]
This PR currently introduces a problem. It crashed on a playlist with a few broken entries

**Comment by Borewit** [comment]
Can you review this PR @touwys?

**Comment by touwys** [comment]
@Borewit 

> Fixes the repair process, on a selection of playlist entries.

Fixed, and well done, thank you. Will you take care of signing off on [#196](https://github.com/Borewit/listFix/issues/196#issue-1826271126)?

> Result what written at the wrong location withing the playlist.

I do not comprehend this remark. Please, elaborate if it is something I should pay attention to?

**Comment by Borewit** [comment]
> Will you take care of signing off on https://github.com/Borewit/listFix/issues/196#issue-1826271126?

Github does close that issue, automatically, it understands "Resolves: #196" and created this relation (see right side):

image

> Result what written at the wrong location within the playlist

Jeremy was a magician with indexes (read index as "track position number"). Operations on the playlist he would forward a list of track indexes to other functions. Then passed the list of indexes to other functions, then those functions would read back the tracks at those positions. Hard to explain, but I just pass the track (objects) to functions. Much simpler and less likely to break. Yet most likely I am the one who introduced this problem while rewriting code.

**Comment by Borewit** [comment]
@touwys, did we also fix #194 with this one?

**Comment by touwys** [comment]
> @touwys, did we also fix #194 with this one?

Yes, I tested it with single tracks, as well as with multiples thereof, and did not notice a recurrence. 

The only thing that has changed on my side from the previous tests, is that I am using only a MP3 media directory as reference for the current test-repairs. Previously, I also had a FLAC media directory in there for reference. I mention it, just in case it bears relation to the upset of the repair results, as we have seen it manifest in this issue.

**Pull request merged**
